---
info:
  app:
    description: Vertica Training SGIJ Production Service
    name: training.vertica.sgij
    version: 0.0.1-SNAPSHOT
    
management:            
  endpoints:
    enabled-by-default: false

server:
  port: 3000
          
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sgij?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: thingtrack
  jpa:  
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        temp:
          use_jdbc_metadata_defaults: false
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: create.sql            
    show-sql: true