//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 09:48:48 PM CEST 
//


package com.thingtrack.training.vertica.sgij.domain;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.thingtrack.sgij.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RegistroCEVDMTipoEvento_QNAME = new QName("http://cnjuego.gob.es/sci/v2.13.xsd", "TipoEvento");
    private final static QName _RegistroCEVDMCompeticion_QNAME = new QName("http://cnjuego.gob.es/sci/v2.13.xsd", "Competicion");
    private final static QName _RegistroCEVDMFechaFin_QNAME = new QName("http://cnjuego.gob.es/sci/v2.13.xsd", "FechaFin");
    private final static QName _RegistroCEVDMActualizado_QNAME = new QName("http://cnjuego.gob.es/sci/v2.13.xsd", "Actualizado");
    private final static QName _RegistroCEVDMOtroDeporteEspecificar_QNAME = new QName("http://cnjuego.gob.es/sci/v2.13.xsd", "OtroDeporteEspecificar");
    private final static QName _RegistroCEVDMFechaInicio_QNAME = new QName("http://cnjuego.gob.es/sci/v2.13.xsd", "FechaInicio");
    private final static QName _RegistroCEVDMDeporte_QNAME = new QName("http://cnjuego.gob.es/sci/v2.13.xsd", "Deporte");
    private final static QName _RegistroCEVDMEventoId_QNAME = new QName("http://cnjuego.gob.es/sci/v2.13.xsd", "EventoId");
    private final static QName _RegistroCEVDMDescripcionEvento_QNAME = new QName("http://cnjuego.gob.es/sci/v2.13.xsd", "DescripcionEvento");
    private final static QName _RegistroJUAFechaAjuste_QNAME = new QName("http://cnjuego.gob.es/sci/v2.13.xsd", "FechaAjuste");
    private final static QName _RegistroJUAImporteAjuste_QNAME = new QName("http://cnjuego.gob.es/sci/v2.13.xsd", "ImporteAjuste");
    private final static QName _RegistroJUATicketApuesta_QNAME = new QName("http://cnjuego.gob.es/sci/v2.13.xsd", "TicketApuesta");
    private final static QName _RegistroJUAMotivoAjuste_QNAME = new QName("http://cnjuego.gob.es/sci/v2.13.xsd", "MotivoAjuste");
    private final static QName _RegistroJUAID_QNAME = new QName("http://cnjuego.gob.es/sci/v2.13.xsd", "ID");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.thingtrack.sgij.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link com.thingtrack.sgij.domain.RegistroJUT.Totales }
     * 
     */
    public com.thingtrack.training.vertica.sgij.domain.RegistroJUT.Totales createRegistroJUTTotales() {
        return new com.thingtrack.training.vertica.sgij.domain.RegistroJUT.Totales();
    }

    /**
     * Create an instance of {@link com.thingtrack.sgij.domain.RegistroJUT.Totales.Botes }
     * 
     */
    public com.thingtrack.training.vertica.sgij.domain.RegistroJUT.Totales.Botes createRegistroJUTTotalesBotes() {
        return new com.thingtrack.training.vertica.sgij.domain.RegistroJUT.Totales.Botes();
    }

    /**
     * Create an instance of {@link RegistroCJD }
     * 
     */
    public RegistroCJD createRegistroCJD() {
        return new RegistroCJD();
    }

    /**
     * Create an instance of {@link RegistroCJD.Jugador }
     * 
     */
    public RegistroCJD.Jugador createRegistroCJDJugador() {
        return new RegistroCJD.Jugador();
    }

    /**
     * Create an instance of {@link DesgloseOperadorTipoJuego }
     * 
     */
    public DesgloseOperadorTipoJuego createDesgloseOperadorTipoJuego() {
        return new DesgloseOperadorTipoJuego();
    }

    /**
     * Create an instance of {@link DesgloseOperador }
     * 
     */
    public DesgloseOperador createDesgloseOperador() {
        return new DesgloseOperador();
    }

    /**
     * Create an instance of {@link RegistroApuesta }
     * 
     */
    public RegistroApuesta createRegistroApuesta() {
        return new RegistroApuesta();
    }

    /**
     * Create an instance of {@link DesgloseOperadorConcepto }
     * 
     */
    public DesgloseOperadorConcepto createDesgloseOperadorConcepto() {
        return new DesgloseOperadorConcepto();
    }

    /**
     * Create an instance of {@link RegistroRUD }
     * 
     */
    public RegistroRUD createRegistroRUD() {
        return new RegistroRUD();
    }

    /**
     * Create an instance of {@link RegistroRUD.Jugador }
     * 
     */
    public RegistroRUD.Jugador createRegistroRUDJugador() {
        return new RegistroRUD.Jugador();
    }

    /**
     * Create an instance of {@link RegistroRUD.Jugador.Estado }
     * 
     */
    public RegistroRUD.Jugador.Estado createRegistroRUDJugadorEstado() {
        return new RegistroRUD.Jugador.Estado();
    }

    /**
     * Create an instance of {@link RegistroCabecera }
     * 
     */
    public RegistroCabecera createRegistroCabecera() {
        return new RegistroCabecera();
    }

    /**
     * Create an instance of {@link RegistroJUD }
     * 
     */
    public RegistroJUD createRegistroJUD() {
        return new RegistroJUD();
    }

    /**
     * Create an instance of {@link RegistroJUD.Jugador }
     * 
     */
    public RegistroJUD.Jugador createRegistroJUDJugador() {
        return new RegistroJUD.Jugador();
    }

    /**
     * Create an instance of {@link RegistroJUD.Jugador.DesgloseCruzadas }
     * 
     */
    public RegistroJUD.Jugador.DesgloseCruzadas createRegistroJUDJugadorDesgloseCruzadas() {
        return new RegistroJUD.Jugador.DesgloseCruzadas();
    }

    /**
     * Create an instance of {@link RegistroRUR }
     * 
     */
    public RegistroRUR createRegistroRUR() {
        return new RegistroRUR();
    }

    /**
     * Create an instance of {@link RegistroRUR.Jugador }
     * 
     */
    public RegistroRUR.Jugador createRegistroRURJugador() {
        return new RegistroRUR.Jugador();
    }

    /**
     * Create an instance of {@link RegistroRUT }
     * 
     */
    public RegistroRUT createRegistroRUT() {
        return new RegistroRUT();
    }

    /**
     * Create an instance of {@link RegistroRUG }
     * 
     */
    public RegistroRUG createRegistroRUG() {
        return new RegistroRUG();
    }

    /**
     * Create an instance of {@link RegistroRUG.Jugador }
     * 
     */
    public RegistroRUG.Jugador createRegistroRUGJugador() {
        return new RegistroRUG.Jugador();
    }

    /**
     * Create an instance of {@link Importe }
     * 
     */
    public Importe createImporte() {
        return new Importe();
    }

    /**
     * Create an instance of {@link DesgloseMedioPago }
     * 
     */
    public DesgloseMedioPago createDesgloseMedioPago() {
        return new DesgloseMedioPago();
    }

    /**
     * Create an instance of {@link RegistroBOT }
     * 
     */
    public RegistroBOT createRegistroBOT() {
        return new RegistroBOT();
    }

    /**
     * Create an instance of {@link RegistroBOT.Botes }
     * 
     */
    public RegistroBOT.Botes createRegistroBOTBotes() {
        return new RegistroBOT.Botes();
    }

    /**
     * Create an instance of {@link RegistroBOT.PartidasVivas }
     * 
     */
    public RegistroBOT.PartidasVivas createRegistroBOTPartidasVivas() {
        return new RegistroBOT.PartidasVivas();
    }

    /**
     * Create an instance of {@link DesgloseOperaciones }
     * 
     */
    public DesgloseOperaciones createDesgloseOperaciones() {
        return new DesgloseOperaciones();
    }

    /**
     * Create an instance of {@link Lote }
     * 
     */
    public Lote createLote() {
        return new Lote();
    }

    /**
     * Create an instance of {@link LoteCabecera }
     * 
     */
    public LoteCabecera createLoteCabecera() {
        return new LoteCabecera();
    }

    /**
     * Create an instance of {@link RegistroPokerCash }
     * 
     */
    public RegistroPokerCash createRegistroPokerCash() {
        return new RegistroPokerCash();
    }

    /**
     * Create an instance of {@link RegistroPuntoBanca }
     * 
     */
    public RegistroPuntoBanca createRegistroPuntoBanca() {
        return new RegistroPuntoBanca();
    }

    /**
     * Create an instance of {@link RegistroPokerTorneo }
     * 
     */
    public RegistroPokerTorneo createRegistroPokerTorneo() {
        return new RegistroPokerTorneo();
    }

    /**
     * Create an instance of {@link RegistroAnulador }
     * 
     */
    public RegistroAnulador createRegistroAnulador() {
        return new RegistroAnulador();
    }

    /**
     * Create an instance of {@link RegistroLoteria }
     * 
     */
    public RegistroLoteria createRegistroLoteria() {
        return new RegistroLoteria();
    }

    /**
     * Create an instance of {@link RegistroJUA }
     * 
     */
    public RegistroJUA createRegistroJUA() {
        return new RegistroJUA();
    }

    /**
     * Create an instance of {@link RegistroOPT }
     * 
     */
    public RegistroOPT createRegistroOPT() {
        return new RegistroOPT();
    }

    /**
     * Create an instance of {@link ID }
     * 
     */
    public ID createID() {
        return new ID();
    }

    /**
     * Create an instance of {@link RegistroBingo }
     * 
     */
    public RegistroBingo createRegistroBingo() {
        return new RegistroBingo();
    }

    /**
     * Create an instance of {@link RegistroORT }
     * 
     */
    public RegistroORT createRegistroORT() {
        return new RegistroORT();
    }

    /**
     * Create an instance of {@link com.thingtrack.sgij.domain.Periodo }
     * 
     */
    public com.thingtrack.training.vertica.sgij.domain.Periodo createPeriodo() {
        return new com.thingtrack.training.vertica.sgij.domain.Periodo();
    }

    /**
     * Create an instance of {@link RegistroCJT }
     * 
     */
    public RegistroCJT createRegistroCJT() {
        return new RegistroCJT();
    }

    /**
     * Create an instance of {@link RegistroCEVDM }
     * 
     */
    public RegistroCEVDM createRegistroCEVDM() {
        return new RegistroCEVDM();
    }

    /**
     * Create an instance of {@link RegistroConcurso }
     * 
     */
    public RegistroConcurso createRegistroConcurso() {
        return new RegistroConcurso();
    }

    /**
     * Create an instance of {@link RegistroSesion }
     * 
     */
    public RegistroSesion createRegistroSesion() {
        return new RegistroSesion();
    }

    /**
     * Create an instance of {@link com.thingtrack.sgij.domain.RegistroJUT.Totales.Botes.Desglose }
     * 
     */
    public com.thingtrack.training.vertica.sgij.domain.RegistroJUT.Totales.Botes.Desglose createRegistroJUTTotalesBotesDesglose() {
        return new com.thingtrack.training.vertica.sgij.domain.RegistroJUT.Totales.Botes.Desglose();
    }

    /**
     * Create an instance of {@link com.thingtrack.sgij.domain.RegistroPeriodicoBase.Periodo }
     * 
     */
    public com.thingtrack.training.vertica.sgij.domain.RegistroPeriodicoBase.Periodo createRegistroPeriodicoBasePeriodo() {
        return new com.thingtrack.training.vertica.sgij.domain.RegistroPeriodicoBase.Periodo();
    }

    /**
     * Create an instance of {@link RegistroCJD.Jugador.Cuentas }
     * 
     */
    public RegistroCJD.Jugador.Cuentas createRegistroCJDJugadorCuentas() {
        return new RegistroCJD.Jugador.Cuentas();
    }

    /**
     * Create an instance of {@link DesgloseOperadorTipoJuego.Desglose }
     * 
     */
    public DesgloseOperadorTipoJuego.Desglose createDesgloseOperadorTipoJuegoDesglose() {
        return new DesgloseOperadorTipoJuego.Desglose();
    }

    /**
     * Create an instance of {@link DesgloseOperador.Desglose }
     * 
     */
    public DesgloseOperador.Desglose createDesgloseOperadorDesglose() {
        return new DesgloseOperador.Desglose();
    }

    /**
     * Create an instance of {@link RegistroApuesta.Eventos }
     * 
     */
    public RegistroApuesta.Eventos createRegistroApuestaEventos() {
        return new RegistroApuesta.Eventos();
    }

    /**
     * Create an instance of {@link DesgloseOperadorConcepto.Desglose }
     * 
     */
    public DesgloseOperadorConcepto.Desglose createDesgloseOperadorConceptoDesglose() {
        return new DesgloseOperadorConcepto.Desglose();
    }

    /**
     * Create an instance of {@link RegistroRUD.Jugador.Residente }
     * 
     */
    public RegistroRUD.Jugador.Residente createRegistroRUDJugadorResidente() {
        return new RegistroRUD.Jugador.Residente();
    }

    /**
     * Create an instance of {@link RegistroRUD.Jugador.NoResidente }
     * 
     */
    public RegistroRUD.Jugador.NoResidente createRegistroRUDJugadorNoResidente() {
        return new RegistroRUD.Jugador.NoResidente();
    }

    /**
     * Create an instance of {@link RegistroRUD.Jugador.Domicilio }
     * 
     */
    public RegistroRUD.Jugador.Domicilio createRegistroRUDJugadorDomicilio() {
        return new RegistroRUD.Jugador.Domicilio();
    }

    /**
     * Create an instance of {@link RegistroRUD.Jugador.LimitesDeposito }
     * 
     */
    public RegistroRUD.Jugador.LimitesDeposito createRegistroRUDJugadorLimitesDeposito() {
        return new RegistroRUD.Jugador.LimitesDeposito();
    }

    /**
     * Create an instance of {@link RegistroRUD.Jugador.Estado.Historico }
     * 
     */
    public RegistroRUD.Jugador.Estado.Historico createRegistroRUDJugadorEstadoHistorico() {
        return new RegistroRUD.Jugador.Estado.Historico();
    }

    /**
     * Create an instance of {@link RegistroCabecera.Rectificacion }
     * 
     */
    public RegistroCabecera.Rectificacion createRegistroCabeceraRectificacion() {
        return new RegistroCabecera.Rectificacion();
    }

    /**
     * Create an instance of {@link RegistroJUD.Jugador.DesgloseEspecie }
     * 
     */
    public RegistroJUD.Jugador.DesgloseEspecie createRegistroJUDJugadorDesgloseEspecie() {
        return new RegistroJUD.Jugador.DesgloseEspecie();
    }

    /**
     * Create an instance of {@link RegistroJUD.Jugador.PlanificacionAzar }
     * 
     */
    public RegistroJUD.Jugador.PlanificacionAzar createRegistroJUDJugadorPlanificacionAzar() {
        return new RegistroJUD.Jugador.PlanificacionAzar();
    }

    /**
     * Create an instance of {@link RegistroJUD.Jugador.DesgloseCruzadas.Cruces }
     * 
     */
    public RegistroJUD.Jugador.DesgloseCruzadas.Cruces createRegistroJUDJugadorDesgloseCruzadasCruces() {
        return new RegistroJUD.Jugador.DesgloseCruzadas.Cruces();
    }

    /**
     * Create an instance of {@link RegistroRUR.Jugador.Estado }
     * 
     */
    public RegistroRUR.Jugador.Estado createRegistroRURJugadorEstado() {
        return new RegistroRUR.Jugador.Estado();
    }

    /**
     * Create an instance of {@link RegistroRUT.NumeroJugadoresPorEstado }
     * 
     */
    public RegistroRUT.NumeroJugadoresPorEstado createRegistroRUTNumeroJugadoresPorEstado() {
        return new RegistroRUT.NumeroJugadoresPorEstado();
    }

    /**
     * Create an instance of {@link RegistroRUG.Jugador.Residente }
     * 
     */
    public RegistroRUG.Jugador.Residente createRegistroRUGJugadorResidente() {
        return new RegistroRUG.Jugador.Residente();
    }

    /**
     * Create an instance of {@link RegistroRUG.Jugador.NoResidente }
     * 
     */
    public RegistroRUG.Jugador.NoResidente createRegistroRUGJugadorNoResidente() {
        return new RegistroRUG.Jugador.NoResidente();
    }

    /**
     * Create an instance of {@link RegistroRUG.Jugador.Domicilio }
     * 
     */
    public RegistroRUG.Jugador.Domicilio createRegistroRUGJugadorDomicilio() {
        return new RegistroRUG.Jugador.Domicilio();
    }

    /**
     * Create an instance of {@link Importe.Linea }
     * 
     */
    public Importe.Linea createImporteLinea() {
        return new Importe.Linea();
    }

    /**
     * Create an instance of {@link DesgloseMedioPago.Desglose }
     * 
     */
    public DesgloseMedioPago.Desglose createDesgloseMedioPagoDesglose() {
        return new DesgloseMedioPago.Desglose();
    }

    /**
     * Create an instance of {@link RegistroBOT.Botes.DesgloseBotes }
     * 
     */
    public RegistroBOT.Botes.DesgloseBotes createRegistroBOTBotesDesgloseBotes() {
        return new RegistroBOT.Botes.DesgloseBotes();
    }

    /**
     * Create an instance of {@link RegistroBOT.PartidasVivas.DesgloseCompromiso }
     * 
     */
    public RegistroBOT.PartidasVivas.DesgloseCompromiso createRegistroBOTPartidasVivasDesgloseCompromiso() {
        return new RegistroBOT.PartidasVivas.DesgloseCompromiso();
    }

    /**
     * Create an instance of {@link DesgloseOperaciones.Operaciones }
     * 
     */
    public DesgloseOperaciones.Operaciones createDesgloseOperacionesOperaciones() {
        return new DesgloseOperaciones.Operaciones();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cnjuego.gob.es/sci/v2.13.xsd", name = "TipoEvento", scope = RegistroCEVDM.class)
    public JAXBElement<String> createRegistroCEVDMTipoEvento(String value) {
        return new JAXBElement<String>(_RegistroCEVDMTipoEvento_QNAME, String.class, RegistroCEVDM.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cnjuego.gob.es/sci/v2.13.xsd", name = "Competicion", scope = RegistroCEVDM.class)
    public JAXBElement<String> createRegistroCEVDMCompeticion(String value) {
        return new JAXBElement<String>(_RegistroCEVDMCompeticion_QNAME, String.class, RegistroCEVDM.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cnjuego.gob.es/sci/v2.13.xsd", name = "FechaFin", scope = RegistroCEVDM.class)
    public JAXBElement<String> createRegistroCEVDMFechaFin(String value) {
        return new JAXBElement<String>(_RegistroCEVDMFechaFin_QNAME, String.class, RegistroCEVDM.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cnjuego.gob.es/sci/v2.13.xsd", name = "Actualizado", scope = RegistroCEVDM.class)
    public JAXBElement<String> createRegistroCEVDMActualizado(String value) {
        return new JAXBElement<String>(_RegistroCEVDMActualizado_QNAME, String.class, RegistroCEVDM.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cnjuego.gob.es/sci/v2.13.xsd", name = "OtroDeporteEspecificar", scope = RegistroCEVDM.class)
    public JAXBElement<String> createRegistroCEVDMOtroDeporteEspecificar(String value) {
        return new JAXBElement<String>(_RegistroCEVDMOtroDeporteEspecificar_QNAME, String.class, RegistroCEVDM.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cnjuego.gob.es/sci/v2.13.xsd", name = "FechaInicio", scope = RegistroCEVDM.class)
    public JAXBElement<String> createRegistroCEVDMFechaInicio(String value) {
        return new JAXBElement<String>(_RegistroCEVDMFechaInicio_QNAME, String.class, RegistroCEVDM.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cnjuego.gob.es/sci/v2.13.xsd", name = "Deporte", scope = RegistroCEVDM.class)
    public JAXBElement<String> createRegistroCEVDMDeporte(String value) {
        return new JAXBElement<String>(_RegistroCEVDMDeporte_QNAME, String.class, RegistroCEVDM.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cnjuego.gob.es/sci/v2.13.xsd", name = "EventoId", scope = RegistroCEVDM.class)
    public JAXBElement<String> createRegistroCEVDMEventoId(String value) {
        return new JAXBElement<String>(_RegistroCEVDMEventoId_QNAME, String.class, RegistroCEVDM.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cnjuego.gob.es/sci/v2.13.xsd", name = "DescripcionEvento", scope = RegistroCEVDM.class)
    public JAXBElement<String> createRegistroCEVDMDescripcionEvento(String value) {
        return new JAXBElement<String>(_RegistroCEVDMDescripcionEvento_QNAME, String.class, RegistroCEVDM.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cnjuego.gob.es/sci/v2.13.xsd", name = "FechaAjuste", scope = RegistroJUA.class)
    public JAXBElement<String> createRegistroJUAFechaAjuste(String value) {
        return new JAXBElement<String>(_RegistroJUAFechaAjuste_QNAME, String.class, RegistroJUA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Importe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cnjuego.gob.es/sci/v2.13.xsd", name = "ImporteAjuste", scope = RegistroJUA.class)
    public JAXBElement<Importe> createRegistroJUAImporteAjuste(Importe value) {
        return new JAXBElement<Importe>(_RegistroJUAImporteAjuste_QNAME, Importe.class, RegistroJUA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cnjuego.gob.es/sci/v2.13.xsd", name = "EventoId", scope = RegistroJUA.class)
    public JAXBElement<String> createRegistroJUAEventoId(String value) {
        return new JAXBElement<String>(_RegistroCEVDMEventoId_QNAME, String.class, RegistroJUA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cnjuego.gob.es/sci/v2.13.xsd", name = "TicketApuesta", scope = RegistroJUA.class)
    public JAXBElement<String> createRegistroJUATicketApuesta(String value) {
        return new JAXBElement<String>(_RegistroJUATicketApuesta_QNAME, String.class, RegistroJUA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cnjuego.gob.es/sci/v2.13.xsd", name = "MotivoAjuste", scope = RegistroJUA.class)
    public JAXBElement<String> createRegistroJUAMotivoAjuste(String value) {
        return new JAXBElement<String>(_RegistroJUAMotivoAjuste_QNAME, String.class, RegistroJUA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ID }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cnjuego.gob.es/sci/v2.13.xsd", name = "ID", scope = RegistroJUA.class)
    public JAXBElement<ID> createRegistroJUAID(ID value) {
        return new JAXBElement<ID>(_RegistroJUAID_QNAME, ID.class, RegistroJUA.class, value);
    }

}
