//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 09:48:48 PM CEST 
//


package com.thingtrack.training.vertica.sgij.domain;

import java.math.BigInteger;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for RegistroLoteria complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegistroLoteria">
 *   &lt;complexContent>
 *     &lt;extension base="{http://cnjuego.gob.es/sci/v2.13.xsd}RegistroJUT">
 *       &lt;sequence>
 *         &lt;element name="NumeroApostantes" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegistroLoteria", propOrder = {
    "numeroApostantes"
})
@Entity(name = "RegistroLoteria")
@Table(name = "REGISTROLOTERIA", schema = "sgij")
public class RegistroLoteria
    extends RegistroJUT
    implements Equals, HashCode
{

    @XmlElement(name = "NumeroApostantes", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numeroApostantes;

    /**
     * Gets the value of the numeroApostantes property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "NUMEROAPOSTANTES", precision = 20, scale = 0)
    public BigInteger getNumeroApostantes() {
        return numeroApostantes;
    }

    /**
     * Sets the value of the numeroApostantes property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumeroApostantes(BigInteger value) {
        this.numeroApostantes = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof RegistroLoteria)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final RegistroLoteria that = ((RegistroLoteria) object);
        {
            BigInteger lhsNumeroApostantes;
            lhsNumeroApostantes = this.getNumeroApostantes();
            BigInteger rhsNumeroApostantes;
            rhsNumeroApostantes = that.getNumeroApostantes();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "numeroApostantes", lhsNumeroApostantes), LocatorUtils.property(thatLocator, "numeroApostantes", rhsNumeroApostantes), lhsNumeroApostantes, rhsNumeroApostantes)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            BigInteger theNumeroApostantes;
            theNumeroApostantes = this.getNumeroApostantes();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "numeroApostantes", theNumeroApostantes), currentHashCode, theNumeroApostantes);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
