//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 09:48:48 PM CEST 
//


package com.thingtrack.training.vertica.sgij.domain;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;
import org.jvnet.hyperjaxb3.item.Item;
import org.jvnet.hyperjaxb3.item.ItemUtils;
import org.jvnet.hyperjaxb3.xml.bind.annotation.adapters.XmlAdapterUtils;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * Nueva versión del CEV para aceptar diarios y mensuales
 * 
 * <p>Java class for RegistroCEVDM complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegistroCEVDM">
 *   &lt;complexContent>
 *     &lt;extension base="{http://cnjuego.gob.es/sci/v2.13.xsd}RegistroPeriodicoBase">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="EventoId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DescripcionEvento" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FechaInicio" type="{http://cnjuego.gob.es/sci/v2.13.xsd}date-aaaammddhhmmssTZ"/>
 *         &lt;element name="FechaFin" type="{http://cnjuego.gob.es/sci/v2.13.xsd}date-aaaammddhhmmssTZ"/>
 *         &lt;element name="TipoEvento">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="D"/>
 *               &lt;enumeration value="H"/>
 *               &lt;enumeration value="O"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Deporte" type="{http://cnjuego.gob.es/sci/v2.13.xsd}ListaDeporte"/>
 *         &lt;element name="OtroDeporteEspecificar" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Competicion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Actualizado" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="S"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegistroCEVDM", propOrder = {
    "eventoIdAndDescripcionEventoAndFechaInicio"
})
@Entity(name = "RegistroCEVDM")
@Table(name = "REGISTROCEVDM", schema = "sgij")
public class RegistroCEVDM
    extends RegistroPeriodicoBase
    implements Equals, HashCode
{

    @XmlElementRefs({
        @XmlElementRef(name = "Competicion", namespace = "http://cnjuego.gob.es/sci/v2.13.xsd", type = JAXBElement.class),
        @XmlElementRef(name = "EventoId", namespace = "http://cnjuego.gob.es/sci/v2.13.xsd", type = JAXBElement.class),
        @XmlElementRef(name = "Actualizado", namespace = "http://cnjuego.gob.es/sci/v2.13.xsd", type = JAXBElement.class),
        @XmlElementRef(name = "FechaInicio", namespace = "http://cnjuego.gob.es/sci/v2.13.xsd", type = JAXBElement.class),
        @XmlElementRef(name = "TipoEvento", namespace = "http://cnjuego.gob.es/sci/v2.13.xsd", type = JAXBElement.class),
        @XmlElementRef(name = "DescripcionEvento", namespace = "http://cnjuego.gob.es/sci/v2.13.xsd", type = JAXBElement.class),
        @XmlElementRef(name = "FechaFin", namespace = "http://cnjuego.gob.es/sci/v2.13.xsd", type = JAXBElement.class),
        @XmlElementRef(name = "Deporte", namespace = "http://cnjuego.gob.es/sci/v2.13.xsd", type = JAXBElement.class),
        @XmlElementRef(name = "OtroDeporteEspecificar", namespace = "http://cnjuego.gob.es/sci/v2.13.xsd", type = JAXBElement.class)
    })
    protected List<JAXBElement<String>> eventoIdAndDescripcionEventoAndFechaInicio;
    protected transient List<RegistroCEVDM.RegistroCEVDMEventoIdAndDescripcionEventoAndFechaInicioItem> eventoIdAndDescripcionEventoAndFechaInicioItems;

    /**
     * Gets the value of the eventoIdAndDescripcionEventoAndFechaInicio property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eventoIdAndDescripcionEventoAndFechaInicio property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEventoIdAndDescripcionEventoAndFechaInicio().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    @Transient
    public List<JAXBElement<String>> getEventoIdAndDescripcionEventoAndFechaInicio() {
        if (eventoIdAndDescripcionEventoAndFechaInicio == null) {
            eventoIdAndDescripcionEventoAndFechaInicio = new ArrayList<JAXBElement<String>>();
        }
        return this.eventoIdAndDescripcionEventoAndFechaInicio;
    }

    /**
     * 
     * 
     */
    public void setEventoIdAndDescripcionEventoAndFechaInicio(List<JAXBElement<String>> eventoIdAndDescripcionEventoAndFechaInicio) {
        this.eventoIdAndDescripcionEventoAndFechaInicio = eventoIdAndDescripcionEventoAndFechaInicio;
    }

    @OneToMany(targetEntity = RegistroCEVDM.RegistroCEVDMEventoIdAndDescripcionEventoAndFechaInicioItem.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "EVENTOIDANDDESCRIPCIONEVENTO_1")
    public List<RegistroCEVDM.RegistroCEVDMEventoIdAndDescripcionEventoAndFechaInicioItem> getEventoIdAndDescripcionEventoAndFechaInicioItems() {
        if (this.eventoIdAndDescripcionEventoAndFechaInicioItems == null) {
            this.eventoIdAndDescripcionEventoAndFechaInicioItems = new ArrayList<RegistroCEVDM.RegistroCEVDMEventoIdAndDescripcionEventoAndFechaInicioItem>();
        }
        if (ItemUtils.shouldBeWrapped(this.eventoIdAndDescripcionEventoAndFechaInicio)) {
            this.eventoIdAndDescripcionEventoAndFechaInicio = ItemUtils.wrap(this.eventoIdAndDescripcionEventoAndFechaInicio, this.eventoIdAndDescripcionEventoAndFechaInicioItems, RegistroCEVDM.RegistroCEVDMEventoIdAndDescripcionEventoAndFechaInicioItem.class);
        }
        return this.eventoIdAndDescripcionEventoAndFechaInicioItems;
    }

    public void setEventoIdAndDescripcionEventoAndFechaInicioItems(List<RegistroCEVDM.RegistroCEVDMEventoIdAndDescripcionEventoAndFechaInicioItem> value) {
        this.eventoIdAndDescripcionEventoAndFechaInicio = null;
        this.eventoIdAndDescripcionEventoAndFechaInicioItems = null;
        this.eventoIdAndDescripcionEventoAndFechaInicioItems = value;
        if (this.eventoIdAndDescripcionEventoAndFechaInicioItems == null) {
            this.eventoIdAndDescripcionEventoAndFechaInicioItems = new ArrayList<RegistroCEVDM.RegistroCEVDMEventoIdAndDescripcionEventoAndFechaInicioItem>();
        }
        if (ItemUtils.shouldBeWrapped(this.eventoIdAndDescripcionEventoAndFechaInicio)) {
            this.eventoIdAndDescripcionEventoAndFechaInicio = ItemUtils.wrap(this.eventoIdAndDescripcionEventoAndFechaInicio, this.eventoIdAndDescripcionEventoAndFechaInicioItems, RegistroCEVDM.RegistroCEVDMEventoIdAndDescripcionEventoAndFechaInicioItem.class);
        }
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof RegistroCEVDM)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final RegistroCEVDM that = ((RegistroCEVDM) object);
        {
            List<JAXBElement<String>> lhsEventoIdAndDescripcionEventoAndFechaInicio;
            lhsEventoIdAndDescripcionEventoAndFechaInicio = (((this.eventoIdAndDescripcionEventoAndFechaInicio!= null)&&(!this.eventoIdAndDescripcionEventoAndFechaInicio.isEmpty()))?this.getEventoIdAndDescripcionEventoAndFechaInicio():null);
            List<JAXBElement<String>> rhsEventoIdAndDescripcionEventoAndFechaInicio;
            rhsEventoIdAndDescripcionEventoAndFechaInicio = (((that.eventoIdAndDescripcionEventoAndFechaInicio!= null)&&(!that.eventoIdAndDescripcionEventoAndFechaInicio.isEmpty()))?that.getEventoIdAndDescripcionEventoAndFechaInicio():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "eventoIdAndDescripcionEventoAndFechaInicio", lhsEventoIdAndDescripcionEventoAndFechaInicio), LocatorUtils.property(thatLocator, "eventoIdAndDescripcionEventoAndFechaInicio", rhsEventoIdAndDescripcionEventoAndFechaInicio), lhsEventoIdAndDescripcionEventoAndFechaInicio, rhsEventoIdAndDescripcionEventoAndFechaInicio)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            List<JAXBElement<String>> theEventoIdAndDescripcionEventoAndFechaInicio;
            theEventoIdAndDescripcionEventoAndFechaInicio = (((this.eventoIdAndDescripcionEventoAndFechaInicio!= null)&&(!this.eventoIdAndDescripcionEventoAndFechaInicio.isEmpty()))?this.getEventoIdAndDescripcionEventoAndFechaInicio():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "eventoIdAndDescripcionEventoAndFechaInicio", theEventoIdAndDescripcionEventoAndFechaInicio), currentHashCode, theEventoIdAndDescripcionEventoAndFechaInicio);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @Entity(name = "RegistroCEVDM$RegistroCEVDMEventoIdAndDescripcionEventoAndFechaInicioItem")
    @Table(name = "REGISTROCEVDMEVENTOIDANDDESC_0", schema = "sgij")
    @Inheritance(strategy = InheritanceType.JOINED)
    public static class RegistroCEVDMEventoIdAndDescripcionEventoAndFechaInicioItem
        implements Item<JAXBElement<String>>
    {

        @XmlElementRefs({
            @XmlElementRef(name = "Competicion", namespace = "http://cnjuego.gob.es/sci/v2.13.xsd", type = JAXBElement.class),
            @XmlElementRef(name = "EventoId", namespace = "http://cnjuego.gob.es/sci/v2.13.xsd", type = JAXBElement.class),
            @XmlElementRef(name = "Actualizado", namespace = "http://cnjuego.gob.es/sci/v2.13.xsd", type = JAXBElement.class),
            @XmlElementRef(name = "FechaInicio", namespace = "http://cnjuego.gob.es/sci/v2.13.xsd", type = JAXBElement.class),
            @XmlElementRef(name = "TipoEvento", namespace = "http://cnjuego.gob.es/sci/v2.13.xsd", type = JAXBElement.class),
            @XmlElementRef(name = "DescripcionEvento", namespace = "http://cnjuego.gob.es/sci/v2.13.xsd", type = JAXBElement.class),
            @XmlElementRef(name = "FechaFin", namespace = "http://cnjuego.gob.es/sci/v2.13.xsd", type = JAXBElement.class),
            @XmlElementRef(name = "Deporte", namespace = "http://cnjuego.gob.es/sci/v2.13.xsd", type = JAXBElement.class),
            @XmlElementRef(name = "OtroDeporteEspecificar", namespace = "http://cnjuego.gob.es/sci/v2.13.xsd", type = JAXBElement.class)
        })
        protected JAXBElement<String> item;
        @XmlAttribute(name = "Hjid")
        protected Long hjid;

        /**
         * 
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        @Transient
        public JAXBElement<String> getItem() {
            return item;
        }

        /**
         * 
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setItem(JAXBElement<String> value) {
            this.item = ((JAXBElement<String> ) value);
        }

        /**
         * Gets the value of the hjid property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        @Id
        @Column(name = "HJID")
        @GeneratedValue(strategy = GenerationType.AUTO)
        public Long getHjid() {
            return hjid;
        }

        /**
         * Sets the value of the hjid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setHjid(Long value) {
            this.hjid = value;
        }

        @Basic
        @Column(name = "ITEMCOMPETICION", length = 255)
        public String getItemCompeticion() {
            if (XmlAdapterUtils.isJAXBElement(String.class, new QName("http://cnjuego.gob.es/sci/v2.13.xsd", "Competicion"), RegistroCEVDM.class, this.getItem())) {
                return XmlAdapterUtils.unmarshallJAXBElement(((JAXBElement<? extends String> ) this.getItem()));
            } else {
                return null;
            }
        }

        public void setItemCompeticion(String target) {
            if (target!= null) {
                setItem(XmlAdapterUtils.marshallJAXBElement(String.class, new QName("http://cnjuego.gob.es/sci/v2.13.xsd", "Competicion"), RegistroCEVDM.class, target));
            }
        }

        @Basic
        @Column(name = "ITEMEVENTOID", length = 255)
        public String getItemEventoId() {
            if (XmlAdapterUtils.isJAXBElement(String.class, new QName("http://cnjuego.gob.es/sci/v2.13.xsd", "EventoId"), RegistroCEVDM.class, this.getItem())) {
                return XmlAdapterUtils.unmarshallJAXBElement(((JAXBElement<? extends String> ) this.getItem()));
            } else {
                return null;
            }
        }

        public void setItemEventoId(String target) {
            if (target!= null) {
                setItem(XmlAdapterUtils.marshallJAXBElement(String.class, new QName("http://cnjuego.gob.es/sci/v2.13.xsd", "EventoId"), RegistroCEVDM.class, target));
            }
        }

        @Basic
        @Column(name = "ITEMACTUALIZADO", length = 255)
        public String getItemActualizado() {
            if (XmlAdapterUtils.isJAXBElement(String.class, new QName("http://cnjuego.gob.es/sci/v2.13.xsd", "Actualizado"), RegistroCEVDM.class, this.getItem())) {
                return XmlAdapterUtils.unmarshallJAXBElement(((JAXBElement<? extends String> ) this.getItem()));
            } else {
                return null;
            }
        }

        public void setItemActualizado(String target) {
            if (target!= null) {
                setItem(XmlAdapterUtils.marshallJAXBElement(String.class, new QName("http://cnjuego.gob.es/sci/v2.13.xsd", "Actualizado"), RegistroCEVDM.class, target));
            }
        }

        @Basic
        @Column(name = "ITEMFECHAINICIO", length = 255)
        public String getItemFechaInicio() {
            if (XmlAdapterUtils.isJAXBElement(String.class, new QName("http://cnjuego.gob.es/sci/v2.13.xsd", "FechaInicio"), RegistroCEVDM.class, this.getItem())) {
                return XmlAdapterUtils.unmarshallJAXBElement(((JAXBElement<? extends String> ) this.getItem()));
            } else {
                return null;
            }
        }

        public void setItemFechaInicio(String target) {
            if (target!= null) {
                setItem(XmlAdapterUtils.marshallJAXBElement(String.class, new QName("http://cnjuego.gob.es/sci/v2.13.xsd", "FechaInicio"), RegistroCEVDM.class, target));
            }
        }

        @Basic
        @Column(name = "ITEMTIPOEVENTO", length = 255)
        public String getItemTipoEvento() {
            if (XmlAdapterUtils.isJAXBElement(String.class, new QName("http://cnjuego.gob.es/sci/v2.13.xsd", "TipoEvento"), RegistroCEVDM.class, this.getItem())) {
                return XmlAdapterUtils.unmarshallJAXBElement(((JAXBElement<? extends String> ) this.getItem()));
            } else {
                return null;
            }
        }

        public void setItemTipoEvento(String target) {
            if (target!= null) {
                setItem(XmlAdapterUtils.marshallJAXBElement(String.class, new QName("http://cnjuego.gob.es/sci/v2.13.xsd", "TipoEvento"), RegistroCEVDM.class, target));
            }
        }

        @Basic
        @Column(name = "ITEMDESCRIPCIONEVENTO", length = 255)
        public String getItemDescripcionEvento() {
            if (XmlAdapterUtils.isJAXBElement(String.class, new QName("http://cnjuego.gob.es/sci/v2.13.xsd", "DescripcionEvento"), RegistroCEVDM.class, this.getItem())) {
                return XmlAdapterUtils.unmarshallJAXBElement(((JAXBElement<? extends String> ) this.getItem()));
            } else {
                return null;
            }
        }

        public void setItemDescripcionEvento(String target) {
            if (target!= null) {
                setItem(XmlAdapterUtils.marshallJAXBElement(String.class, new QName("http://cnjuego.gob.es/sci/v2.13.xsd", "DescripcionEvento"), RegistroCEVDM.class, target));
            }
        }

        @Basic
        @Column(name = "ITEMFECHAFIN", length = 255)
        public String getItemFechaFin() {
            if (XmlAdapterUtils.isJAXBElement(String.class, new QName("http://cnjuego.gob.es/sci/v2.13.xsd", "FechaFin"), RegistroCEVDM.class, this.getItem())) {
                return XmlAdapterUtils.unmarshallJAXBElement(((JAXBElement<? extends String> ) this.getItem()));
            } else {
                return null;
            }
        }

        public void setItemFechaFin(String target) {
            if (target!= null) {
                setItem(XmlAdapterUtils.marshallJAXBElement(String.class, new QName("http://cnjuego.gob.es/sci/v2.13.xsd", "FechaFin"), RegistroCEVDM.class, target));
            }
        }

        @Basic
        @Column(name = "ITEMDEPORTE", length = 255)
        public String getItemDeporte() {
            if (XmlAdapterUtils.isJAXBElement(String.class, new QName("http://cnjuego.gob.es/sci/v2.13.xsd", "Deporte"), RegistroCEVDM.class, this.getItem())) {
                return XmlAdapterUtils.unmarshallJAXBElement(((JAXBElement<? extends String> ) this.getItem()));
            } else {
                return null;
            }
        }

        public void setItemDeporte(String target) {
            if (target!= null) {
                setItem(XmlAdapterUtils.marshallJAXBElement(String.class, new QName("http://cnjuego.gob.es/sci/v2.13.xsd", "Deporte"), RegistroCEVDM.class, target));
            }
        }

        @Basic
        @Column(name = "ITEMOTRODEPORTEESPECIFICAR", length = 255)
        public String getItemOtroDeporteEspecificar() {
            if (XmlAdapterUtils.isJAXBElement(String.class, new QName("http://cnjuego.gob.es/sci/v2.13.xsd", "OtroDeporteEspecificar"), RegistroCEVDM.class, this.getItem())) {
                return XmlAdapterUtils.unmarshallJAXBElement(((JAXBElement<? extends String> ) this.getItem()));
            } else {
                return null;
            }
        }

        public void setItemOtroDeporteEspecificar(String target) {
            if (target!= null) {
                setItem(XmlAdapterUtils.marshallJAXBElement(String.class, new QName("http://cnjuego.gob.es/sci/v2.13.xsd", "OtroDeporteEspecificar"), RegistroCEVDM.class, target));
            }
        }

    }

}
