//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 09:48:48 PM CEST 
//


package com.thingtrack.training.vertica.sgij.domain;

import java.math.BigInteger;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for RegistroPokerTorneo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegistroPokerTorneo">
 *   &lt;complexContent>
 *     &lt;extension base="{http://cnjuego.gob.es/sci/v2.13.xsd}RegistroJUT">
 *       &lt;sequence>
 *         &lt;element name="Variante">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="DR"/>
 *               &lt;enumeration value="ST"/>
 *               &lt;enumeration value="OM"/>
 *               &lt;enumeration value="TH"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="VarianteComercial" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NumeroParticipantes" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegistroPokerTorneo", propOrder = {
    "variante",
    "varianteComercial",
    "numeroParticipantes"
})
@Entity(name = "RegistroPokerTorneo")
@Table(name = "REGISTROPOKERTORNEO", schema = "sgij")
public class RegistroPokerTorneo
    extends RegistroJUT
    implements Equals, HashCode
{

    @XmlElement(name = "Variante", required = true)
    protected String variante;
    @XmlElement(name = "VarianteComercial")
    protected String varianteComercial;
    @XmlElement(name = "NumeroParticipantes", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numeroParticipantes;

    /**
     * Gets the value of the variante property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "VARIANTE")
    public String getVariante() {
        return variante;
    }

    /**
     * Sets the value of the variante property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVariante(String value) {
        this.variante = value;
    }

    /**
     * Gets the value of the varianteComercial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "VARIANTECOMERCIAL", length = 255)
    public String getVarianteComercial() {
        return varianteComercial;
    }

    /**
     * Sets the value of the varianteComercial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVarianteComercial(String value) {
        this.varianteComercial = value;
    }

    /**
     * Gets the value of the numeroParticipantes property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "NUMEROPARTICIPANTES", precision = 20, scale = 0)
    public BigInteger getNumeroParticipantes() {
        return numeroParticipantes;
    }

    /**
     * Sets the value of the numeroParticipantes property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumeroParticipantes(BigInteger value) {
        this.numeroParticipantes = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof RegistroPokerTorneo)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final RegistroPokerTorneo that = ((RegistroPokerTorneo) object);
        {
            String lhsVariante;
            lhsVariante = this.getVariante();
            String rhsVariante;
            rhsVariante = that.getVariante();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "variante", lhsVariante), LocatorUtils.property(thatLocator, "variante", rhsVariante), lhsVariante, rhsVariante)) {
                return false;
            }
        }
        {
            String lhsVarianteComercial;
            lhsVarianteComercial = this.getVarianteComercial();
            String rhsVarianteComercial;
            rhsVarianteComercial = that.getVarianteComercial();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "varianteComercial", lhsVarianteComercial), LocatorUtils.property(thatLocator, "varianteComercial", rhsVarianteComercial), lhsVarianteComercial, rhsVarianteComercial)) {
                return false;
            }
        }
        {
            BigInteger lhsNumeroParticipantes;
            lhsNumeroParticipantes = this.getNumeroParticipantes();
            BigInteger rhsNumeroParticipantes;
            rhsNumeroParticipantes = that.getNumeroParticipantes();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "numeroParticipantes", lhsNumeroParticipantes), LocatorUtils.property(thatLocator, "numeroParticipantes", rhsNumeroParticipantes), lhsNumeroParticipantes, rhsNumeroParticipantes)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            String theVariante;
            theVariante = this.getVariante();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "variante", theVariante), currentHashCode, theVariante);
        }
        {
            String theVarianteComercial;
            theVarianteComercial = this.getVarianteComercial();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "varianteComercial", theVarianteComercial), currentHashCode, theVarianteComercial);
        }
        {
            BigInteger theNumeroParticipantes;
            theNumeroParticipantes = this.getNumeroParticipantes();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "numeroParticipantes", theNumeroParticipantes), currentHashCode, theNumeroParticipantes);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
