//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 09:48:48 PM CEST 
//


package com.thingtrack.training.vertica.sgij.domain;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for RegistroCJT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegistroCJT">
 *   &lt;complexContent>
 *     &lt;extension base="{http://cnjuego.gob.es/sci/v2.13.xsd}RegistroPeriodicoBase">
 *       &lt;sequence>
 *         &lt;element name="SaldoInicial" type="{http://cnjuego.gob.es/sci/v2.13.xsd}Importe"/>
 *         &lt;element name="Depositos" type="{http://cnjuego.gob.es/sci/v2.13.xsd}DesgloseMedioPago"/>
 *         &lt;element name="Retiradas" type="{http://cnjuego.gob.es/sci/v2.13.xsd}DesgloseMedioPago"/>
 *         &lt;element name="Participacion" type="{http://cnjuego.gob.es/sci/v2.13.xsd}DesgloseOperadorTipoJuego"/>
 *         &lt;element name="ParticipacionDevolucion" type="{http://cnjuego.gob.es/sci/v2.13.xsd}DesgloseOperadorTipoJuego"/>
 *         &lt;element name="Premios" type="{http://cnjuego.gob.es/sci/v2.13.xsd}DesgloseOperadorTipoJuego"/>
 *         &lt;element name="Otros" type="{http://cnjuego.gob.es/sci/v2.13.xsd}DesgloseOperadorConcepto"/>
 *         &lt;element name="SaldoFinal" type="{http://cnjuego.gob.es/sci/v2.13.xsd}Importe"/>
 *         &lt;element name="PremiosEspecie" type="{http://cnjuego.gob.es/sci/v2.13.xsd}DesgloseOperadorTipoJuego"/>
 *         &lt;element name="AjustePremios" type="{http://cnjuego.gob.es/sci/v2.13.xsd}DesgloseOperadorTipoJuego"/>
 *         &lt;element name="Trans_IN" type="{http://cnjuego.gob.es/sci/v2.13.xsd}DesgloseOperador"/>
 *         &lt;element name="Trans_OUT" type="{http://cnjuego.gob.es/sci/v2.13.xsd}DesgloseOperador"/>
 *         &lt;element name="Comision" type="{http://cnjuego.gob.es/sci/v2.13.xsd}DesgloseOperadorTipoJuego"/>
 *         &lt;element name="Bonos" type="{http://cnjuego.gob.es/sci/v2.13.xsd}DesgloseOperadorConcepto"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegistroCJT", propOrder = {
    "saldoInicial",
    "depositos",
    "retiradas",
    "participacion",
    "participacionDevolucion",
    "premios",
    "otros",
    "saldoFinal",
    "premiosEspecie",
    "ajustePremios",
    "transIN",
    "transOUT",
    "comision",
    "bonos"
})
@Entity(name = "RegistroCJT")
@Table(name = "REGISTROCJT", schema = "sgij")
public class RegistroCJT
    extends RegistroPeriodicoBase
    implements Equals, HashCode
{

    @XmlElement(name = "SaldoInicial", required = true)
    protected Importe saldoInicial;
    @XmlElement(name = "Depositos", required = true)
    protected DesgloseMedioPago depositos;
    @XmlElement(name = "Retiradas", required = true)
    protected DesgloseMedioPago retiradas;
    @XmlElement(name = "Participacion", required = true)
    protected DesgloseOperadorTipoJuego participacion;
    @XmlElement(name = "ParticipacionDevolucion", required = true)
    protected DesgloseOperadorTipoJuego participacionDevolucion;
    @XmlElement(name = "Premios", required = true)
    protected DesgloseOperadorTipoJuego premios;
    @XmlElement(name = "Otros", required = true)
    protected DesgloseOperadorConcepto otros;
    @XmlElement(name = "SaldoFinal", required = true)
    protected Importe saldoFinal;
    @XmlElement(name = "PremiosEspecie", required = true)
    protected DesgloseOperadorTipoJuego premiosEspecie;
    @XmlElement(name = "AjustePremios", required = true)
    protected DesgloseOperadorTipoJuego ajustePremios;
    @XmlElement(name = "Trans_IN", required = true)
    protected DesgloseOperador transIN;
    @XmlElement(name = "Trans_OUT", required = true)
    protected DesgloseOperador transOUT;
    @XmlElement(name = "Comision", required = true)
    protected DesgloseOperadorTipoJuego comision;
    @XmlElement(name = "Bonos", required = true)
    protected DesgloseOperadorConcepto bonos;

    /**
     * Gets the value of the saldoInicial property.
     * 
     * @return
     *     possible object is
     *     {@link Importe }
     *     
     */
    @ManyToOne(targetEntity = Importe.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "SALDOINICIAL_REGISTROCJT_HJID")
    public Importe getSaldoInicial() {
        return saldoInicial;
    }

    /**
     * Sets the value of the saldoInicial property.
     * 
     * @param value
     *     allowed object is
     *     {@link Importe }
     *     
     */
    public void setSaldoInicial(Importe value) {
        this.saldoInicial = value;
    }

    /**
     * Gets the value of the depositos property.
     * 
     * @return
     *     possible object is
     *     {@link DesgloseMedioPago }
     *     
     */
    @ManyToOne(targetEntity = DesgloseMedioPago.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "DEPOSITOS_REGISTROCJT_HJID")
    public DesgloseMedioPago getDepositos() {
        return depositos;
    }

    /**
     * Sets the value of the depositos property.
     * 
     * @param value
     *     allowed object is
     *     {@link DesgloseMedioPago }
     *     
     */
    public void setDepositos(DesgloseMedioPago value) {
        this.depositos = value;
    }

    /**
     * Gets the value of the retiradas property.
     * 
     * @return
     *     possible object is
     *     {@link DesgloseMedioPago }
     *     
     */
    @ManyToOne(targetEntity = DesgloseMedioPago.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "RETIRADAS_REGISTROCJT_HJID")
    public DesgloseMedioPago getRetiradas() {
        return retiradas;
    }

    /**
     * Sets the value of the retiradas property.
     * 
     * @param value
     *     allowed object is
     *     {@link DesgloseMedioPago }
     *     
     */
    public void setRetiradas(DesgloseMedioPago value) {
        this.retiradas = value;
    }

    /**
     * Gets the value of the participacion property.
     * 
     * @return
     *     possible object is
     *     {@link DesgloseOperadorTipoJuego }
     *     
     */
    @ManyToOne(targetEntity = DesgloseOperadorTipoJuego.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "PARTICIPACION_REGISTROCJT_HJ_0")
    public DesgloseOperadorTipoJuego getParticipacion() {
        return participacion;
    }

    /**
     * Sets the value of the participacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link DesgloseOperadorTipoJuego }
     *     
     */
    public void setParticipacion(DesgloseOperadorTipoJuego value) {
        this.participacion = value;
    }

    /**
     * Gets the value of the participacionDevolucion property.
     * 
     * @return
     *     possible object is
     *     {@link DesgloseOperadorTipoJuego }
     *     
     */
    @ManyToOne(targetEntity = DesgloseOperadorTipoJuego.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "PARTICIPACIONDEVOLUCION_REGI_2")
    public DesgloseOperadorTipoJuego getParticipacionDevolucion() {
        return participacionDevolucion;
    }

    /**
     * Sets the value of the participacionDevolucion property.
     * 
     * @param value
     *     allowed object is
     *     {@link DesgloseOperadorTipoJuego }
     *     
     */
    public void setParticipacionDevolucion(DesgloseOperadorTipoJuego value) {
        this.participacionDevolucion = value;
    }

    /**
     * Gets the value of the premios property.
     * 
     * @return
     *     possible object is
     *     {@link DesgloseOperadorTipoJuego }
     *     
     */
    @ManyToOne(targetEntity = DesgloseOperadorTipoJuego.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "PREMIOS_REGISTROCJT_HJID")
    public DesgloseOperadorTipoJuego getPremios() {
        return premios;
    }

    /**
     * Sets the value of the premios property.
     * 
     * @param value
     *     allowed object is
     *     {@link DesgloseOperadorTipoJuego }
     *     
     */
    public void setPremios(DesgloseOperadorTipoJuego value) {
        this.premios = value;
    }

    /**
     * Gets the value of the otros property.
     * 
     * @return
     *     possible object is
     *     {@link DesgloseOperadorConcepto }
     *     
     */
    @ManyToOne(targetEntity = DesgloseOperadorConcepto.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "OTROS_REGISTROCJT_HJID")
    public DesgloseOperadorConcepto getOtros() {
        return otros;
    }

    /**
     * Sets the value of the otros property.
     * 
     * @param value
     *     allowed object is
     *     {@link DesgloseOperadorConcepto }
     *     
     */
    public void setOtros(DesgloseOperadorConcepto value) {
        this.otros = value;
    }

    /**
     * Gets the value of the saldoFinal property.
     * 
     * @return
     *     possible object is
     *     {@link Importe }
     *     
     */
    @ManyToOne(targetEntity = Importe.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "SALDOFINAL_REGISTROCJT_HJID")
    public Importe getSaldoFinal() {
        return saldoFinal;
    }

    /**
     * Sets the value of the saldoFinal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Importe }
     *     
     */
    public void setSaldoFinal(Importe value) {
        this.saldoFinal = value;
    }

    /**
     * Gets the value of the premiosEspecie property.
     * 
     * @return
     *     possible object is
     *     {@link DesgloseOperadorTipoJuego }
     *     
     */
    @ManyToOne(targetEntity = DesgloseOperadorTipoJuego.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "PREMIOSESPECIE_REGISTROCJT_H_0")
    public DesgloseOperadorTipoJuego getPremiosEspecie() {
        return premiosEspecie;
    }

    /**
     * Sets the value of the premiosEspecie property.
     * 
     * @param value
     *     allowed object is
     *     {@link DesgloseOperadorTipoJuego }
     *     
     */
    public void setPremiosEspecie(DesgloseOperadorTipoJuego value) {
        this.premiosEspecie = value;
    }

    /**
     * Gets the value of the ajustePremios property.
     * 
     * @return
     *     possible object is
     *     {@link DesgloseOperadorTipoJuego }
     *     
     */
    @ManyToOne(targetEntity = DesgloseOperadorTipoJuego.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "AJUSTEPREMIOS_REGISTROCJT_HJ_0")
    public DesgloseOperadorTipoJuego getAjustePremios() {
        return ajustePremios;
    }

    /**
     * Sets the value of the ajustePremios property.
     * 
     * @param value
     *     allowed object is
     *     {@link DesgloseOperadorTipoJuego }
     *     
     */
    public void setAjustePremios(DesgloseOperadorTipoJuego value) {
        this.ajustePremios = value;
    }

    /**
     * Gets the value of the transIN property.
     * 
     * @return
     *     possible object is
     *     {@link DesgloseOperador }
     *     
     */
    @ManyToOne(targetEntity = DesgloseOperador.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "TRANSIN_REGISTROCJT_HJID")
    public DesgloseOperador getTransIN() {
        return transIN;
    }

    /**
     * Sets the value of the transIN property.
     * 
     * @param value
     *     allowed object is
     *     {@link DesgloseOperador }
     *     
     */
    public void setTransIN(DesgloseOperador value) {
        this.transIN = value;
    }

    /**
     * Gets the value of the transOUT property.
     * 
     * @return
     *     possible object is
     *     {@link DesgloseOperador }
     *     
     */
    @ManyToOne(targetEntity = DesgloseOperador.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "TRANSOUT_REGISTROCJT_HJID")
    public DesgloseOperador getTransOUT() {
        return transOUT;
    }

    /**
     * Sets the value of the transOUT property.
     * 
     * @param value
     *     allowed object is
     *     {@link DesgloseOperador }
     *     
     */
    public void setTransOUT(DesgloseOperador value) {
        this.transOUT = value;
    }

    /**
     * Gets the value of the comision property.
     * 
     * @return
     *     possible object is
     *     {@link DesgloseOperadorTipoJuego }
     *     
     */
    @ManyToOne(targetEntity = DesgloseOperadorTipoJuego.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "COMISION_REGISTROCJT_HJID")
    public DesgloseOperadorTipoJuego getComision() {
        return comision;
    }

    /**
     * Sets the value of the comision property.
     * 
     * @param value
     *     allowed object is
     *     {@link DesgloseOperadorTipoJuego }
     *     
     */
    public void setComision(DesgloseOperadorTipoJuego value) {
        this.comision = value;
    }

    /**
     * Gets the value of the bonos property.
     * 
     * @return
     *     possible object is
     *     {@link DesgloseOperadorConcepto }
     *     
     */
    @ManyToOne(targetEntity = DesgloseOperadorConcepto.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "BONOS_REGISTROCJT_HJID")
    public DesgloseOperadorConcepto getBonos() {
        return bonos;
    }

    /**
     * Sets the value of the bonos property.
     * 
     * @param value
     *     allowed object is
     *     {@link DesgloseOperadorConcepto }
     *     
     */
    public void setBonos(DesgloseOperadorConcepto value) {
        this.bonos = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof RegistroCJT)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final RegistroCJT that = ((RegistroCJT) object);
        {
            Importe lhsSaldoInicial;
            lhsSaldoInicial = this.getSaldoInicial();
            Importe rhsSaldoInicial;
            rhsSaldoInicial = that.getSaldoInicial();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "saldoInicial", lhsSaldoInicial), LocatorUtils.property(thatLocator, "saldoInicial", rhsSaldoInicial), lhsSaldoInicial, rhsSaldoInicial)) {
                return false;
            }
        }
        {
            DesgloseMedioPago lhsDepositos;
            lhsDepositos = this.getDepositos();
            DesgloseMedioPago rhsDepositos;
            rhsDepositos = that.getDepositos();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "depositos", lhsDepositos), LocatorUtils.property(thatLocator, "depositos", rhsDepositos), lhsDepositos, rhsDepositos)) {
                return false;
            }
        }
        {
            DesgloseMedioPago lhsRetiradas;
            lhsRetiradas = this.getRetiradas();
            DesgloseMedioPago rhsRetiradas;
            rhsRetiradas = that.getRetiradas();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "retiradas", lhsRetiradas), LocatorUtils.property(thatLocator, "retiradas", rhsRetiradas), lhsRetiradas, rhsRetiradas)) {
                return false;
            }
        }
        {
            DesgloseOperadorTipoJuego lhsParticipacion;
            lhsParticipacion = this.getParticipacion();
            DesgloseOperadorTipoJuego rhsParticipacion;
            rhsParticipacion = that.getParticipacion();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "participacion", lhsParticipacion), LocatorUtils.property(thatLocator, "participacion", rhsParticipacion), lhsParticipacion, rhsParticipacion)) {
                return false;
            }
        }
        {
            DesgloseOperadorTipoJuego lhsParticipacionDevolucion;
            lhsParticipacionDevolucion = this.getParticipacionDevolucion();
            DesgloseOperadorTipoJuego rhsParticipacionDevolucion;
            rhsParticipacionDevolucion = that.getParticipacionDevolucion();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "participacionDevolucion", lhsParticipacionDevolucion), LocatorUtils.property(thatLocator, "participacionDevolucion", rhsParticipacionDevolucion), lhsParticipacionDevolucion, rhsParticipacionDevolucion)) {
                return false;
            }
        }
        {
            DesgloseOperadorTipoJuego lhsPremios;
            lhsPremios = this.getPremios();
            DesgloseOperadorTipoJuego rhsPremios;
            rhsPremios = that.getPremios();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "premios", lhsPremios), LocatorUtils.property(thatLocator, "premios", rhsPremios), lhsPremios, rhsPremios)) {
                return false;
            }
        }
        {
            DesgloseOperadorConcepto lhsOtros;
            lhsOtros = this.getOtros();
            DesgloseOperadorConcepto rhsOtros;
            rhsOtros = that.getOtros();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "otros", lhsOtros), LocatorUtils.property(thatLocator, "otros", rhsOtros), lhsOtros, rhsOtros)) {
                return false;
            }
        }
        {
            Importe lhsSaldoFinal;
            lhsSaldoFinal = this.getSaldoFinal();
            Importe rhsSaldoFinal;
            rhsSaldoFinal = that.getSaldoFinal();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "saldoFinal", lhsSaldoFinal), LocatorUtils.property(thatLocator, "saldoFinal", rhsSaldoFinal), lhsSaldoFinal, rhsSaldoFinal)) {
                return false;
            }
        }
        {
            DesgloseOperadorTipoJuego lhsPremiosEspecie;
            lhsPremiosEspecie = this.getPremiosEspecie();
            DesgloseOperadorTipoJuego rhsPremiosEspecie;
            rhsPremiosEspecie = that.getPremiosEspecie();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "premiosEspecie", lhsPremiosEspecie), LocatorUtils.property(thatLocator, "premiosEspecie", rhsPremiosEspecie), lhsPremiosEspecie, rhsPremiosEspecie)) {
                return false;
            }
        }
        {
            DesgloseOperadorTipoJuego lhsAjustePremios;
            lhsAjustePremios = this.getAjustePremios();
            DesgloseOperadorTipoJuego rhsAjustePremios;
            rhsAjustePremios = that.getAjustePremios();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "ajustePremios", lhsAjustePremios), LocatorUtils.property(thatLocator, "ajustePremios", rhsAjustePremios), lhsAjustePremios, rhsAjustePremios)) {
                return false;
            }
        }
        {
            DesgloseOperador lhsTransIN;
            lhsTransIN = this.getTransIN();
            DesgloseOperador rhsTransIN;
            rhsTransIN = that.getTransIN();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "transIN", lhsTransIN), LocatorUtils.property(thatLocator, "transIN", rhsTransIN), lhsTransIN, rhsTransIN)) {
                return false;
            }
        }
        {
            DesgloseOperador lhsTransOUT;
            lhsTransOUT = this.getTransOUT();
            DesgloseOperador rhsTransOUT;
            rhsTransOUT = that.getTransOUT();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "transOUT", lhsTransOUT), LocatorUtils.property(thatLocator, "transOUT", rhsTransOUT), lhsTransOUT, rhsTransOUT)) {
                return false;
            }
        }
        {
            DesgloseOperadorTipoJuego lhsComision;
            lhsComision = this.getComision();
            DesgloseOperadorTipoJuego rhsComision;
            rhsComision = that.getComision();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "comision", lhsComision), LocatorUtils.property(thatLocator, "comision", rhsComision), lhsComision, rhsComision)) {
                return false;
            }
        }
        {
            DesgloseOperadorConcepto lhsBonos;
            lhsBonos = this.getBonos();
            DesgloseOperadorConcepto rhsBonos;
            rhsBonos = that.getBonos();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "bonos", lhsBonos), LocatorUtils.property(thatLocator, "bonos", rhsBonos), lhsBonos, rhsBonos)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            Importe theSaldoInicial;
            theSaldoInicial = this.getSaldoInicial();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "saldoInicial", theSaldoInicial), currentHashCode, theSaldoInicial);
        }
        {
            DesgloseMedioPago theDepositos;
            theDepositos = this.getDepositos();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "depositos", theDepositos), currentHashCode, theDepositos);
        }
        {
            DesgloseMedioPago theRetiradas;
            theRetiradas = this.getRetiradas();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "retiradas", theRetiradas), currentHashCode, theRetiradas);
        }
        {
            DesgloseOperadorTipoJuego theParticipacion;
            theParticipacion = this.getParticipacion();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "participacion", theParticipacion), currentHashCode, theParticipacion);
        }
        {
            DesgloseOperadorTipoJuego theParticipacionDevolucion;
            theParticipacionDevolucion = this.getParticipacionDevolucion();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "participacionDevolucion", theParticipacionDevolucion), currentHashCode, theParticipacionDevolucion);
        }
        {
            DesgloseOperadorTipoJuego thePremios;
            thePremios = this.getPremios();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "premios", thePremios), currentHashCode, thePremios);
        }
        {
            DesgloseOperadorConcepto theOtros;
            theOtros = this.getOtros();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "otros", theOtros), currentHashCode, theOtros);
        }
        {
            Importe theSaldoFinal;
            theSaldoFinal = this.getSaldoFinal();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "saldoFinal", theSaldoFinal), currentHashCode, theSaldoFinal);
        }
        {
            DesgloseOperadorTipoJuego thePremiosEspecie;
            thePremiosEspecie = this.getPremiosEspecie();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "premiosEspecie", thePremiosEspecie), currentHashCode, thePremiosEspecie);
        }
        {
            DesgloseOperadorTipoJuego theAjustePremios;
            theAjustePremios = this.getAjustePremios();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "ajustePremios", theAjustePremios), currentHashCode, theAjustePremios);
        }
        {
            DesgloseOperador theTransIN;
            theTransIN = this.getTransIN();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "transIN", theTransIN), currentHashCode, theTransIN);
        }
        {
            DesgloseOperador theTransOUT;
            theTransOUT = this.getTransOUT();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "transOUT", theTransOUT), currentHashCode, theTransOUT);
        }
        {
            DesgloseOperadorTipoJuego theComision;
            theComision = this.getComision();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "comision", theComision), currentHashCode, theComision);
        }
        {
            DesgloseOperadorConcepto theBonos;
            theBonos = this.getBonos();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "bonos", theBonos), currentHashCode, theBonos);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
