//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 09:48:48 PM CEST 
//


package com.thingtrack.training.vertica.sgij.domain;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for RegistroBOT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegistroBOT">
 *   &lt;complexContent>
 *     &lt;extension base="{http://cnjuego.gob.es/sci/v2.13.xsd}RegistroMensualBase">
 *       &lt;sequence>
 *         &lt;element name="TipoJuego" type="{http://cnjuego.gob.es/sci/v2.13.xsd}TipoJuego"/>
 *         &lt;element name="PartidasVivas">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SaldoInicial" type="{http://cnjuego.gob.es/sci/v2.13.xsd}Importe"/>
 *                   &lt;element name="Movimientos" type="{http://cnjuego.gob.es/sci/v2.13.xsd}Importe"/>
 *                   &lt;element name="SaldoFinal" type="{http://cnjuego.gob.es/sci/v2.13.xsd}Importe"/>
 *                   &lt;element name="DesgloseCompromiso" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Fecha" type="{http://cnjuego.gob.es/sci/v2.13.xsd}date-aaaamm"/>
 *                             &lt;element name="SaldoFinal" type="{http://cnjuego.gob.es/sci/v2.13.xsd}Importe"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Botes">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SaldoInicial" type="{http://cnjuego.gob.es/sci/v2.13.xsd}Importe"/>
 *                   &lt;element name="Movimientos" type="{http://cnjuego.gob.es/sci/v2.13.xsd}Importe"/>
 *                   &lt;element name="SaldoFinal" type="{http://cnjuego.gob.es/sci/v2.13.xsd}Importe"/>
 *                   &lt;element name="DesgloseBotes" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="BoteId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="BoteDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="FechaInicio" type="{http://cnjuego.gob.es/sci/v2.13.xsd}date-aaaammdd"/>
 *                             &lt;element name="FechaFin" type="{http://cnjuego.gob.es/sci/v2.13.xsd}date-aaaammdd" minOccurs="0"/>
 *                             &lt;element name="SaldoInicial" type="{http://cnjuego.gob.es/sci/v2.13.xsd}Importe"/>
 *                             &lt;element name="Movimientos" type="{http://cnjuego.gob.es/sci/v2.13.xsd}Importe"/>
 *                             &lt;element name="SaldoFinal" type="{http://cnjuego.gob.es/sci/v2.13.xsd}Importe"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegistroBOT", propOrder = {
    "tipoJuego",
    "partidasVivas",
    "botes"
})
@Entity(name = "RegistroBOT")
@Table(name = "REGISTROBOT", schema = "sgij")
public class RegistroBOT
    extends RegistroMensualBase
    implements Equals, HashCode
{

    @XmlElement(name = "TipoJuego", required = true)
    protected TipoJuego tipoJuego;
    @XmlElement(name = "PartidasVivas", required = true)
    protected RegistroBOT.PartidasVivas partidasVivas;
    @XmlElement(name = "Botes", required = true)
    protected RegistroBOT.Botes botes;

    /**
     * Gets the value of the tipoJuego property.
     * 
     * @return
     *     possible object is
     *     {@link TipoJuego }
     *     
     */
    @Basic
    @Column(name = "TIPOJUEGO", length = 255)
    @Enumerated(EnumType.STRING)
    public TipoJuego getTipoJuego() {
        return tipoJuego;
    }

    /**
     * Sets the value of the tipoJuego property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoJuego }
     *     
     */
    public void setTipoJuego(TipoJuego value) {
        this.tipoJuego = value;
    }

    /**
     * Gets the value of the partidasVivas property.
     * 
     * @return
     *     possible object is
     *     {@link RegistroBOT.PartidasVivas }
     *     
     */
    @ManyToOne(targetEntity = RegistroBOT.PartidasVivas.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "PARTIDASVIVAS_REGISTROBOT_HJ_0")
    public RegistroBOT.PartidasVivas getPartidasVivas() {
        return partidasVivas;
    }

    /**
     * Sets the value of the partidasVivas property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegistroBOT.PartidasVivas }
     *     
     */
    public void setPartidasVivas(RegistroBOT.PartidasVivas value) {
        this.partidasVivas = value;
    }

    /**
     * Gets the value of the botes property.
     * 
     * @return
     *     possible object is
     *     {@link RegistroBOT.Botes }
     *     
     */
    @ManyToOne(targetEntity = RegistroBOT.Botes.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "BOTES_REGISTROBOT_HJID")
    public RegistroBOT.Botes getBotes() {
        return botes;
    }

    /**
     * Sets the value of the botes property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegistroBOT.Botes }
     *     
     */
    public void setBotes(RegistroBOT.Botes value) {
        this.botes = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof RegistroBOT)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final RegistroBOT that = ((RegistroBOT) object);
        {
            TipoJuego lhsTipoJuego;
            lhsTipoJuego = this.getTipoJuego();
            TipoJuego rhsTipoJuego;
            rhsTipoJuego = that.getTipoJuego();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "tipoJuego", lhsTipoJuego), LocatorUtils.property(thatLocator, "tipoJuego", rhsTipoJuego), lhsTipoJuego, rhsTipoJuego)) {
                return false;
            }
        }
        {
            RegistroBOT.PartidasVivas lhsPartidasVivas;
            lhsPartidasVivas = this.getPartidasVivas();
            RegistroBOT.PartidasVivas rhsPartidasVivas;
            rhsPartidasVivas = that.getPartidasVivas();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "partidasVivas", lhsPartidasVivas), LocatorUtils.property(thatLocator, "partidasVivas", rhsPartidasVivas), lhsPartidasVivas, rhsPartidasVivas)) {
                return false;
            }
        }
        {
            RegistroBOT.Botes lhsBotes;
            lhsBotes = this.getBotes();
            RegistroBOT.Botes rhsBotes;
            rhsBotes = that.getBotes();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "botes", lhsBotes), LocatorUtils.property(thatLocator, "botes", rhsBotes), lhsBotes, rhsBotes)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            TipoJuego theTipoJuego;
            theTipoJuego = this.getTipoJuego();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "tipoJuego", theTipoJuego), currentHashCode, theTipoJuego);
        }
        {
            RegistroBOT.PartidasVivas thePartidasVivas;
            thePartidasVivas = this.getPartidasVivas();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "partidasVivas", thePartidasVivas), currentHashCode, thePartidasVivas);
        }
        {
            RegistroBOT.Botes theBotes;
            theBotes = this.getBotes();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "botes", theBotes), currentHashCode, theBotes);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SaldoInicial" type="{http://cnjuego.gob.es/sci/v2.13.xsd}Importe"/>
     *         &lt;element name="Movimientos" type="{http://cnjuego.gob.es/sci/v2.13.xsd}Importe"/>
     *         &lt;element name="SaldoFinal" type="{http://cnjuego.gob.es/sci/v2.13.xsd}Importe"/>
     *         &lt;element name="DesgloseBotes" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="BoteId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="BoteDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="FechaInicio" type="{http://cnjuego.gob.es/sci/v2.13.xsd}date-aaaammdd"/>
     *                   &lt;element name="FechaFin" type="{http://cnjuego.gob.es/sci/v2.13.xsd}date-aaaammdd" minOccurs="0"/>
     *                   &lt;element name="SaldoInicial" type="{http://cnjuego.gob.es/sci/v2.13.xsd}Importe"/>
     *                   &lt;element name="Movimientos" type="{http://cnjuego.gob.es/sci/v2.13.xsd}Importe"/>
     *                   &lt;element name="SaldoFinal" type="{http://cnjuego.gob.es/sci/v2.13.xsd}Importe"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "saldoInicial",
        "movimientos",
        "saldoFinal",
        "desgloseBotes"
    })
    @Entity(name = "RegistroBOT$Botes")
    @Table(name = "BOTES_0", schema = "sgij")
    @Inheritance(strategy = InheritanceType.JOINED)
    public static class Botes
        implements Equals, HashCode
    {

        @XmlElement(name = "SaldoInicial", required = true)
        protected Importe saldoInicial;
        @XmlElement(name = "Movimientos", required = true)
        protected Importe movimientos;
        @XmlElement(name = "SaldoFinal", required = true)
        protected Importe saldoFinal;
        @XmlElement(name = "DesgloseBotes")
        protected List<RegistroBOT.Botes.DesgloseBotes> desgloseBotes;
        @XmlAttribute(name = "Hjid")
        protected Long hjid;

        /**
         * Gets the value of the saldoInicial property.
         * 
         * @return
         *     possible object is
         *     {@link Importe }
         *     
         */
        @ManyToOne(targetEntity = Importe.class, cascade = {
            CascadeType.ALL
        })
        @JoinColumn(name = "SALDOINICIAL_BOTES_0_HJID")
        public Importe getSaldoInicial() {
            return saldoInicial;
        }

        /**
         * Sets the value of the saldoInicial property.
         * 
         * @param value
         *     allowed object is
         *     {@link Importe }
         *     
         */
        public void setSaldoInicial(Importe value) {
            this.saldoInicial = value;
        }

        /**
         * Gets the value of the movimientos property.
         * 
         * @return
         *     possible object is
         *     {@link Importe }
         *     
         */
        @ManyToOne(targetEntity = Importe.class, cascade = {
            CascadeType.ALL
        })
        @JoinColumn(name = "MOVIMIENTOS_BOTES_0_HJID")
        public Importe getMovimientos() {
            return movimientos;
        }

        /**
         * Sets the value of the movimientos property.
         * 
         * @param value
         *     allowed object is
         *     {@link Importe }
         *     
         */
        public void setMovimientos(Importe value) {
            this.movimientos = value;
        }

        /**
         * Gets the value of the saldoFinal property.
         * 
         * @return
         *     possible object is
         *     {@link Importe }
         *     
         */
        @ManyToOne(targetEntity = Importe.class, cascade = {
            CascadeType.ALL
        })
        @JoinColumn(name = "SALDOFINAL_BOTES_0_HJID")
        public Importe getSaldoFinal() {
            return saldoFinal;
        }

        /**
         * Sets the value of the saldoFinal property.
         * 
         * @param value
         *     allowed object is
         *     {@link Importe }
         *     
         */
        public void setSaldoFinal(Importe value) {
            this.saldoFinal = value;
        }

        /**
         * Gets the value of the desgloseBotes property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the desgloseBotes property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDesgloseBotes().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RegistroBOT.Botes.DesgloseBotes }
         * 
         * 
         */
        @OneToMany(targetEntity = com.thingtrack.training.vertica.sgij.domain.RegistroBOT.Botes.DesgloseBotes.class, cascade = {
            CascadeType.ALL
        })
        @JoinColumn(name = "DESGLOSEBOTES_BOTES_0_HJID")
        public List<RegistroBOT.Botes.DesgloseBotes> getDesgloseBotes() {
            if (desgloseBotes == null) {
                desgloseBotes = new ArrayList<RegistroBOT.Botes.DesgloseBotes>();
            }
            return this.desgloseBotes;
        }

        /**
         * 
         * 
         */
        public void setDesgloseBotes(List<RegistroBOT.Botes.DesgloseBotes> desgloseBotes) {
            this.desgloseBotes = desgloseBotes;
        }

        /**
         * Gets the value of the hjid property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        @Id
        @Column(name = "HJID")
        @GeneratedValue(strategy = GenerationType.AUTO)
        public Long getHjid() {
            return hjid;
        }

        /**
         * Sets the value of the hjid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setHjid(Long value) {
            this.hjid = value;
        }

        public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
            if (!(object instanceof RegistroBOT.Botes)) {
                return false;
            }
            if (this == object) {
                return true;
            }
            final RegistroBOT.Botes that = ((RegistroBOT.Botes) object);
            {
                Importe lhsSaldoInicial;
                lhsSaldoInicial = this.getSaldoInicial();
                Importe rhsSaldoInicial;
                rhsSaldoInicial = that.getSaldoInicial();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "saldoInicial", lhsSaldoInicial), LocatorUtils.property(thatLocator, "saldoInicial", rhsSaldoInicial), lhsSaldoInicial, rhsSaldoInicial)) {
                    return false;
                }
            }
            {
                Importe lhsMovimientos;
                lhsMovimientos = this.getMovimientos();
                Importe rhsMovimientos;
                rhsMovimientos = that.getMovimientos();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "movimientos", lhsMovimientos), LocatorUtils.property(thatLocator, "movimientos", rhsMovimientos), lhsMovimientos, rhsMovimientos)) {
                    return false;
                }
            }
            {
                Importe lhsSaldoFinal;
                lhsSaldoFinal = this.getSaldoFinal();
                Importe rhsSaldoFinal;
                rhsSaldoFinal = that.getSaldoFinal();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "saldoFinal", lhsSaldoFinal), LocatorUtils.property(thatLocator, "saldoFinal", rhsSaldoFinal), lhsSaldoFinal, rhsSaldoFinal)) {
                    return false;
                }
            }
            {
                List<RegistroBOT.Botes.DesgloseBotes> lhsDesgloseBotes;
                lhsDesgloseBotes = (((this.desgloseBotes!= null)&&(!this.desgloseBotes.isEmpty()))?this.getDesgloseBotes():null);
                List<RegistroBOT.Botes.DesgloseBotes> rhsDesgloseBotes;
                rhsDesgloseBotes = (((that.desgloseBotes!= null)&&(!that.desgloseBotes.isEmpty()))?that.getDesgloseBotes():null);
                if (!strategy.equals(LocatorUtils.property(thisLocator, "desgloseBotes", lhsDesgloseBotes), LocatorUtils.property(thatLocator, "desgloseBotes", rhsDesgloseBotes), lhsDesgloseBotes, rhsDesgloseBotes)) {
                    return false;
                }
            }
            return true;
        }

        public boolean equals(Object object) {
            final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
            return equals(null, null, object, strategy);
        }

        public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
            int currentHashCode = 1;
            {
                Importe theSaldoInicial;
                theSaldoInicial = this.getSaldoInicial();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "saldoInicial", theSaldoInicial), currentHashCode, theSaldoInicial);
            }
            {
                Importe theMovimientos;
                theMovimientos = this.getMovimientos();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "movimientos", theMovimientos), currentHashCode, theMovimientos);
            }
            {
                Importe theSaldoFinal;
                theSaldoFinal = this.getSaldoFinal();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "saldoFinal", theSaldoFinal), currentHashCode, theSaldoFinal);
            }
            {
                List<RegistroBOT.Botes.DesgloseBotes> theDesgloseBotes;
                theDesgloseBotes = (((this.desgloseBotes!= null)&&(!this.desgloseBotes.isEmpty()))?this.getDesgloseBotes():null);
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "desgloseBotes", theDesgloseBotes), currentHashCode, theDesgloseBotes);
            }
            return currentHashCode;
        }

        public int hashCode() {
            final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
            return this.hashCode(null, strategy);
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="BoteId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="BoteDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="FechaInicio" type="{http://cnjuego.gob.es/sci/v2.13.xsd}date-aaaammdd"/>
         *         &lt;element name="FechaFin" type="{http://cnjuego.gob.es/sci/v2.13.xsd}date-aaaammdd" minOccurs="0"/>
         *         &lt;element name="SaldoInicial" type="{http://cnjuego.gob.es/sci/v2.13.xsd}Importe"/>
         *         &lt;element name="Movimientos" type="{http://cnjuego.gob.es/sci/v2.13.xsd}Importe"/>
         *         &lt;element name="SaldoFinal" type="{http://cnjuego.gob.es/sci/v2.13.xsd}Importe"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "boteId",
            "boteDesc",
            "fechaInicio",
            "fechaFin",
            "saldoInicial",
            "movimientos",
            "saldoFinal"
        })
        @Entity(name = "RegistroBOT$Botes$DesgloseBotes")
        @Table(name = "DESGLOSEBOTES", schema = "sgij")
        @Inheritance(strategy = InheritanceType.JOINED)
        public static class DesgloseBotes
            implements Equals, HashCode
        {

            @XmlElement(name = "BoteId", required = true)
            protected String boteId;
            @XmlElement(name = "BoteDesc", required = true)
            protected String boteDesc;
            @XmlElement(name = "FechaInicio", required = true)
            protected String fechaInicio;
            @XmlElement(name = "FechaFin")
            protected String fechaFin;
            @XmlElement(name = "SaldoInicial", required = true)
            protected Importe saldoInicial;
            @XmlElement(name = "Movimientos", required = true)
            protected Importe movimientos;
            @XmlElement(name = "SaldoFinal", required = true)
            protected Importe saldoFinal;
            @XmlAttribute(name = "Hjid")
            protected Long hjid;

            /**
             * Gets the value of the boteId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @Basic
            @Column(name = "BOTEID", length = 255)
            public String getBoteId() {
                return boteId;
            }

            /**
             * Sets the value of the boteId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBoteId(String value) {
                this.boteId = value;
            }

            /**
             * Gets the value of the boteDesc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @Basic
            @Column(name = "BOTEDESC", length = 255)
            public String getBoteDesc() {
                return boteDesc;
            }

            /**
             * Sets the value of the boteDesc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBoteDesc(String value) {
                this.boteDesc = value;
            }

            /**
             * Gets the value of the fechaInicio property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @Basic
            @Column(name = "FECHAINICIO", length = 255)
            public String getFechaInicio() {
                return fechaInicio;
            }

            /**
             * Sets the value of the fechaInicio property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFechaInicio(String value) {
                this.fechaInicio = value;
            }

            /**
             * Gets the value of the fechaFin property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @Basic
            @Column(name = "FECHAFIN", length = 255)
            public String getFechaFin() {
                return fechaFin;
            }

            /**
             * Sets the value of the fechaFin property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFechaFin(String value) {
                this.fechaFin = value;
            }

            /**
             * Gets the value of the saldoInicial property.
             * 
             * @return
             *     possible object is
             *     {@link Importe }
             *     
             */
            @ManyToOne(targetEntity = Importe.class, cascade = {
                CascadeType.ALL
            })
            @JoinColumn(name = "SALDOINICIAL_DESGLOSEBOTES_H_0")
            public Importe getSaldoInicial() {
                return saldoInicial;
            }

            /**
             * Sets the value of the saldoInicial property.
             * 
             * @param value
             *     allowed object is
             *     {@link Importe }
             *     
             */
            public void setSaldoInicial(Importe value) {
                this.saldoInicial = value;
            }

            /**
             * Gets the value of the movimientos property.
             * 
             * @return
             *     possible object is
             *     {@link Importe }
             *     
             */
            @ManyToOne(targetEntity = Importe.class, cascade = {
                CascadeType.ALL
            })
            @JoinColumn(name = "MOVIMIENTOS_DESGLOSEBOTES_HJ_0")
            public Importe getMovimientos() {
                return movimientos;
            }

            /**
             * Sets the value of the movimientos property.
             * 
             * @param value
             *     allowed object is
             *     {@link Importe }
             *     
             */
            public void setMovimientos(Importe value) {
                this.movimientos = value;
            }

            /**
             * Gets the value of the saldoFinal property.
             * 
             * @return
             *     possible object is
             *     {@link Importe }
             *     
             */
            @ManyToOne(targetEntity = Importe.class, cascade = {
                CascadeType.ALL
            })
            @JoinColumn(name = "SALDOFINAL_DESGLOSEBOTES_HJID")
            public Importe getSaldoFinal() {
                return saldoFinal;
            }

            /**
             * Sets the value of the saldoFinal property.
             * 
             * @param value
             *     allowed object is
             *     {@link Importe }
             *     
             */
            public void setSaldoFinal(Importe value) {
                this.saldoFinal = value;
            }

            /**
             * Gets the value of the hjid property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            @Id
            @Column(name = "HJID")
            @GeneratedValue(strategy = GenerationType.AUTO)
            public Long getHjid() {
                return hjid;
            }

            /**
             * Sets the value of the hjid property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setHjid(Long value) {
                this.hjid = value;
            }

            public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
                if (!(object instanceof RegistroBOT.Botes.DesgloseBotes)) {
                    return false;
                }
                if (this == object) {
                    return true;
                }
                final RegistroBOT.Botes.DesgloseBotes that = ((RegistroBOT.Botes.DesgloseBotes) object);
                {
                    String lhsBoteId;
                    lhsBoteId = this.getBoteId();
                    String rhsBoteId;
                    rhsBoteId = that.getBoteId();
                    if (!strategy.equals(LocatorUtils.property(thisLocator, "boteId", lhsBoteId), LocatorUtils.property(thatLocator, "boteId", rhsBoteId), lhsBoteId, rhsBoteId)) {
                        return false;
                    }
                }
                {
                    String lhsBoteDesc;
                    lhsBoteDesc = this.getBoteDesc();
                    String rhsBoteDesc;
                    rhsBoteDesc = that.getBoteDesc();
                    if (!strategy.equals(LocatorUtils.property(thisLocator, "boteDesc", lhsBoteDesc), LocatorUtils.property(thatLocator, "boteDesc", rhsBoteDesc), lhsBoteDesc, rhsBoteDesc)) {
                        return false;
                    }
                }
                {
                    String lhsFechaInicio;
                    lhsFechaInicio = this.getFechaInicio();
                    String rhsFechaInicio;
                    rhsFechaInicio = that.getFechaInicio();
                    if (!strategy.equals(LocatorUtils.property(thisLocator, "fechaInicio", lhsFechaInicio), LocatorUtils.property(thatLocator, "fechaInicio", rhsFechaInicio), lhsFechaInicio, rhsFechaInicio)) {
                        return false;
                    }
                }
                {
                    String lhsFechaFin;
                    lhsFechaFin = this.getFechaFin();
                    String rhsFechaFin;
                    rhsFechaFin = that.getFechaFin();
                    if (!strategy.equals(LocatorUtils.property(thisLocator, "fechaFin", lhsFechaFin), LocatorUtils.property(thatLocator, "fechaFin", rhsFechaFin), lhsFechaFin, rhsFechaFin)) {
                        return false;
                    }
                }
                {
                    Importe lhsSaldoInicial;
                    lhsSaldoInicial = this.getSaldoInicial();
                    Importe rhsSaldoInicial;
                    rhsSaldoInicial = that.getSaldoInicial();
                    if (!strategy.equals(LocatorUtils.property(thisLocator, "saldoInicial", lhsSaldoInicial), LocatorUtils.property(thatLocator, "saldoInicial", rhsSaldoInicial), lhsSaldoInicial, rhsSaldoInicial)) {
                        return false;
                    }
                }
                {
                    Importe lhsMovimientos;
                    lhsMovimientos = this.getMovimientos();
                    Importe rhsMovimientos;
                    rhsMovimientos = that.getMovimientos();
                    if (!strategy.equals(LocatorUtils.property(thisLocator, "movimientos", lhsMovimientos), LocatorUtils.property(thatLocator, "movimientos", rhsMovimientos), lhsMovimientos, rhsMovimientos)) {
                        return false;
                    }
                }
                {
                    Importe lhsSaldoFinal;
                    lhsSaldoFinal = this.getSaldoFinal();
                    Importe rhsSaldoFinal;
                    rhsSaldoFinal = that.getSaldoFinal();
                    if (!strategy.equals(LocatorUtils.property(thisLocator, "saldoFinal", lhsSaldoFinal), LocatorUtils.property(thatLocator, "saldoFinal", rhsSaldoFinal), lhsSaldoFinal, rhsSaldoFinal)) {
                        return false;
                    }
                }
                return true;
            }

            public boolean equals(Object object) {
                final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
                return equals(null, null, object, strategy);
            }

            public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
                int currentHashCode = 1;
                {
                    String theBoteId;
                    theBoteId = this.getBoteId();
                    currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "boteId", theBoteId), currentHashCode, theBoteId);
                }
                {
                    String theBoteDesc;
                    theBoteDesc = this.getBoteDesc();
                    currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "boteDesc", theBoteDesc), currentHashCode, theBoteDesc);
                }
                {
                    String theFechaInicio;
                    theFechaInicio = this.getFechaInicio();
                    currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "fechaInicio", theFechaInicio), currentHashCode, theFechaInicio);
                }
                {
                    String theFechaFin;
                    theFechaFin = this.getFechaFin();
                    currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "fechaFin", theFechaFin), currentHashCode, theFechaFin);
                }
                {
                    Importe theSaldoInicial;
                    theSaldoInicial = this.getSaldoInicial();
                    currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "saldoInicial", theSaldoInicial), currentHashCode, theSaldoInicial);
                }
                {
                    Importe theMovimientos;
                    theMovimientos = this.getMovimientos();
                    currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "movimientos", theMovimientos), currentHashCode, theMovimientos);
                }
                {
                    Importe theSaldoFinal;
                    theSaldoFinal = this.getSaldoFinal();
                    currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "saldoFinal", theSaldoFinal), currentHashCode, theSaldoFinal);
                }
                return currentHashCode;
            }

            public int hashCode() {
                final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
                return this.hashCode(null, strategy);
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SaldoInicial" type="{http://cnjuego.gob.es/sci/v2.13.xsd}Importe"/>
     *         &lt;element name="Movimientos" type="{http://cnjuego.gob.es/sci/v2.13.xsd}Importe"/>
     *         &lt;element name="SaldoFinal" type="{http://cnjuego.gob.es/sci/v2.13.xsd}Importe"/>
     *         &lt;element name="DesgloseCompromiso" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Fecha" type="{http://cnjuego.gob.es/sci/v2.13.xsd}date-aaaamm"/>
     *                   &lt;element name="SaldoFinal" type="{http://cnjuego.gob.es/sci/v2.13.xsd}Importe"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "saldoInicial",
        "movimientos",
        "saldoFinal",
        "desgloseCompromiso"
    })
    @Entity(name = "RegistroBOT$PartidasVivas")
    @Table(name = "PARTIDASVIVAS", schema = "sgij")
    @Inheritance(strategy = InheritanceType.JOINED)
    public static class PartidasVivas
        implements Equals, HashCode
    {

        @XmlElement(name = "SaldoInicial", required = true)
        protected Importe saldoInicial;
        @XmlElement(name = "Movimientos", required = true)
        protected Importe movimientos;
        @XmlElement(name = "SaldoFinal", required = true)
        protected Importe saldoFinal;
        @XmlElement(name = "DesgloseCompromiso")
        protected List<RegistroBOT.PartidasVivas.DesgloseCompromiso> desgloseCompromiso;
        @XmlAttribute(name = "Hjid")
        protected Long hjid;

        /**
         * Gets the value of the saldoInicial property.
         * 
         * @return
         *     possible object is
         *     {@link Importe }
         *     
         */
        @ManyToOne(targetEntity = Importe.class, cascade = {
            CascadeType.ALL
        })
        @JoinColumn(name = "SALDOINICIAL_PARTIDASVIVAS_H_0")
        public Importe getSaldoInicial() {
            return saldoInicial;
        }

        /**
         * Sets the value of the saldoInicial property.
         * 
         * @param value
         *     allowed object is
         *     {@link Importe }
         *     
         */
        public void setSaldoInicial(Importe value) {
            this.saldoInicial = value;
        }

        /**
         * Gets the value of the movimientos property.
         * 
         * @return
         *     possible object is
         *     {@link Importe }
         *     
         */
        @ManyToOne(targetEntity = Importe.class, cascade = {
            CascadeType.ALL
        })
        @JoinColumn(name = "MOVIMIENTOS_PARTIDASVIVAS_HJ_0")
        public Importe getMovimientos() {
            return movimientos;
        }

        /**
         * Sets the value of the movimientos property.
         * 
         * @param value
         *     allowed object is
         *     {@link Importe }
         *     
         */
        public void setMovimientos(Importe value) {
            this.movimientos = value;
        }

        /**
         * Gets the value of the saldoFinal property.
         * 
         * @return
         *     possible object is
         *     {@link Importe }
         *     
         */
        @ManyToOne(targetEntity = Importe.class, cascade = {
            CascadeType.ALL
        })
        @JoinColumn(name = "SALDOFINAL_PARTIDASVIVAS_HJID")
        public Importe getSaldoFinal() {
            return saldoFinal;
        }

        /**
         * Sets the value of the saldoFinal property.
         * 
         * @param value
         *     allowed object is
         *     {@link Importe }
         *     
         */
        public void setSaldoFinal(Importe value) {
            this.saldoFinal = value;
        }

        /**
         * Gets the value of the desgloseCompromiso property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the desgloseCompromiso property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDesgloseCompromiso().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RegistroBOT.PartidasVivas.DesgloseCompromiso }
         * 
         * 
         */
        @OneToMany(targetEntity = com.thingtrack.training.vertica.sgij.domain.RegistroBOT.PartidasVivas.DesgloseCompromiso.class, cascade = {
            CascadeType.ALL
        })
        @JoinColumn(name = "DESGLOSECOMPROMISO_PARTIDASV_0")
        public List<RegistroBOT.PartidasVivas.DesgloseCompromiso> getDesgloseCompromiso() {
            if (desgloseCompromiso == null) {
                desgloseCompromiso = new ArrayList<RegistroBOT.PartidasVivas.DesgloseCompromiso>();
            }
            return this.desgloseCompromiso;
        }

        /**
         * 
         * 
         */
        public void setDesgloseCompromiso(List<RegistroBOT.PartidasVivas.DesgloseCompromiso> desgloseCompromiso) {
            this.desgloseCompromiso = desgloseCompromiso;
        }

        /**
         * Gets the value of the hjid property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        @Id
        @Column(name = "HJID")
        @GeneratedValue(strategy = GenerationType.AUTO)
        public Long getHjid() {
            return hjid;
        }

        /**
         * Sets the value of the hjid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setHjid(Long value) {
            this.hjid = value;
        }

        public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
            if (!(object instanceof RegistroBOT.PartidasVivas)) {
                return false;
            }
            if (this == object) {
                return true;
            }
            final RegistroBOT.PartidasVivas that = ((RegistroBOT.PartidasVivas) object);
            {
                Importe lhsSaldoInicial;
                lhsSaldoInicial = this.getSaldoInicial();
                Importe rhsSaldoInicial;
                rhsSaldoInicial = that.getSaldoInicial();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "saldoInicial", lhsSaldoInicial), LocatorUtils.property(thatLocator, "saldoInicial", rhsSaldoInicial), lhsSaldoInicial, rhsSaldoInicial)) {
                    return false;
                }
            }
            {
                Importe lhsMovimientos;
                lhsMovimientos = this.getMovimientos();
                Importe rhsMovimientos;
                rhsMovimientos = that.getMovimientos();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "movimientos", lhsMovimientos), LocatorUtils.property(thatLocator, "movimientos", rhsMovimientos), lhsMovimientos, rhsMovimientos)) {
                    return false;
                }
            }
            {
                Importe lhsSaldoFinal;
                lhsSaldoFinal = this.getSaldoFinal();
                Importe rhsSaldoFinal;
                rhsSaldoFinal = that.getSaldoFinal();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "saldoFinal", lhsSaldoFinal), LocatorUtils.property(thatLocator, "saldoFinal", rhsSaldoFinal), lhsSaldoFinal, rhsSaldoFinal)) {
                    return false;
                }
            }
            {
                List<RegistroBOT.PartidasVivas.DesgloseCompromiso> lhsDesgloseCompromiso;
                lhsDesgloseCompromiso = (((this.desgloseCompromiso!= null)&&(!this.desgloseCompromiso.isEmpty()))?this.getDesgloseCompromiso():null);
                List<RegistroBOT.PartidasVivas.DesgloseCompromiso> rhsDesgloseCompromiso;
                rhsDesgloseCompromiso = (((that.desgloseCompromiso!= null)&&(!that.desgloseCompromiso.isEmpty()))?that.getDesgloseCompromiso():null);
                if (!strategy.equals(LocatorUtils.property(thisLocator, "desgloseCompromiso", lhsDesgloseCompromiso), LocatorUtils.property(thatLocator, "desgloseCompromiso", rhsDesgloseCompromiso), lhsDesgloseCompromiso, rhsDesgloseCompromiso)) {
                    return false;
                }
            }
            return true;
        }

        public boolean equals(Object object) {
            final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
            return equals(null, null, object, strategy);
        }

        public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
            int currentHashCode = 1;
            {
                Importe theSaldoInicial;
                theSaldoInicial = this.getSaldoInicial();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "saldoInicial", theSaldoInicial), currentHashCode, theSaldoInicial);
            }
            {
                Importe theMovimientos;
                theMovimientos = this.getMovimientos();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "movimientos", theMovimientos), currentHashCode, theMovimientos);
            }
            {
                Importe theSaldoFinal;
                theSaldoFinal = this.getSaldoFinal();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "saldoFinal", theSaldoFinal), currentHashCode, theSaldoFinal);
            }
            {
                List<RegistroBOT.PartidasVivas.DesgloseCompromiso> theDesgloseCompromiso;
                theDesgloseCompromiso = (((this.desgloseCompromiso!= null)&&(!this.desgloseCompromiso.isEmpty()))?this.getDesgloseCompromiso():null);
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "desgloseCompromiso", theDesgloseCompromiso), currentHashCode, theDesgloseCompromiso);
            }
            return currentHashCode;
        }

        public int hashCode() {
            final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
            return this.hashCode(null, strategy);
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Fecha" type="{http://cnjuego.gob.es/sci/v2.13.xsd}date-aaaamm"/>
         *         &lt;element name="SaldoFinal" type="{http://cnjuego.gob.es/sci/v2.13.xsd}Importe"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "fecha",
            "saldoFinal"
        })
        @Entity(name = "RegistroBOT$PartidasVivas$DesgloseCompromiso")
        @Table(name = "DESGLOSECOMPROMISO", schema = "sgij")
        @Inheritance(strategy = InheritanceType.JOINED)
        public static class DesgloseCompromiso
            implements Equals, HashCode
        {

            @XmlElement(name = "Fecha", required = true)
            protected String fecha;
            @XmlElement(name = "SaldoFinal", required = true)
            protected Importe saldoFinal;
            @XmlAttribute(name = "Hjid")
            protected Long hjid;

            /**
             * Gets the value of the fecha property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @Basic
            @Column(name = "FECHA", length = 255)
            public String getFecha() {
                return fecha;
            }

            /**
             * Sets the value of the fecha property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFecha(String value) {
                this.fecha = value;
            }

            /**
             * Gets the value of the saldoFinal property.
             * 
             * @return
             *     possible object is
             *     {@link Importe }
             *     
             */
            @ManyToOne(targetEntity = Importe.class, cascade = {
                CascadeType.ALL
            })
            @JoinColumn(name = "SALDOFINAL_DESGLOSECOMPROMIS_0")
            public Importe getSaldoFinal() {
                return saldoFinal;
            }

            /**
             * Sets the value of the saldoFinal property.
             * 
             * @param value
             *     allowed object is
             *     {@link Importe }
             *     
             */
            public void setSaldoFinal(Importe value) {
                this.saldoFinal = value;
            }

            /**
             * Gets the value of the hjid property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            @Id
            @Column(name = "HJID")
            @GeneratedValue(strategy = GenerationType.AUTO)
            public Long getHjid() {
                return hjid;
            }

            /**
             * Sets the value of the hjid property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setHjid(Long value) {
                this.hjid = value;
            }

            public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
                if (!(object instanceof RegistroBOT.PartidasVivas.DesgloseCompromiso)) {
                    return false;
                }
                if (this == object) {
                    return true;
                }
                final RegistroBOT.PartidasVivas.DesgloseCompromiso that = ((RegistroBOT.PartidasVivas.DesgloseCompromiso) object);
                {
                    String lhsFecha;
                    lhsFecha = this.getFecha();
                    String rhsFecha;
                    rhsFecha = that.getFecha();
                    if (!strategy.equals(LocatorUtils.property(thisLocator, "fecha", lhsFecha), LocatorUtils.property(thatLocator, "fecha", rhsFecha), lhsFecha, rhsFecha)) {
                        return false;
                    }
                }
                {
                    Importe lhsSaldoFinal;
                    lhsSaldoFinal = this.getSaldoFinal();
                    Importe rhsSaldoFinal;
                    rhsSaldoFinal = that.getSaldoFinal();
                    if (!strategy.equals(LocatorUtils.property(thisLocator, "saldoFinal", lhsSaldoFinal), LocatorUtils.property(thatLocator, "saldoFinal", rhsSaldoFinal), lhsSaldoFinal, rhsSaldoFinal)) {
                        return false;
                    }
                }
                return true;
            }

            public boolean equals(Object object) {
                final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
                return equals(null, null, object, strategy);
            }

            public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
                int currentHashCode = 1;
                {
                    String theFecha;
                    theFecha = this.getFecha();
                    currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "fecha", theFecha), currentHashCode, theFecha);
                }
                {
                    Importe theSaldoFinal;
                    theSaldoFinal = this.getSaldoFinal();
                    currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "saldoFinal", theSaldoFinal), currentHashCode, theSaldoFinal);
                }
                return currentHashCode;
            }

            public int hashCode() {
                final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
                return this.hashCode(null, strategy);
            }

        }

    }

}
