//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 09:48:48 PM CEST 
//


package com.thingtrack.training.vertica.sgij.domain;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for RegistroOPT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegistroOPT">
 *   &lt;complexContent>
 *     &lt;extension base="{http://cnjuego.gob.es/sci/v2.13.xsd}RegistroMensualBase">
 *       &lt;sequence>
 *         &lt;element name="TipoJuego" type="{http://cnjuego.gob.es/sci/v2.13.xsd}TipoJuego"/>
 *         &lt;element name="Participacion" type="{http://cnjuego.gob.es/sci/v2.13.xsd}DesgloseOperador"/>
 *         &lt;element name="ParticipacionDevolucion" type="{http://cnjuego.gob.es/sci/v2.13.xsd}DesgloseOperador"/>
 *         &lt;element name="Premios" type="{http://cnjuego.gob.es/sci/v2.13.xsd}DesgloseOperador"/>
 *         &lt;element name="PremiosEspecie" type="{http://cnjuego.gob.es/sci/v2.13.xsd}DesgloseOperador"/>
 *         &lt;element name="Botes" type="{http://cnjuego.gob.es/sci/v2.13.xsd}DesgloseOperador"/>
 *         &lt;element name="AjustesRed" type="{http://cnjuego.gob.es/sci/v2.13.xsd}DesgloseOperador"/>
 *         &lt;element name="Otros" type="{http://cnjuego.gob.es/sci/v2.13.xsd}DesgloseOperadorConcepto"/>
 *         &lt;element name="Comision" type="{http://cnjuego.gob.es/sci/v2.13.xsd}DesgloseOperador"/>
 *         &lt;element name="GGR" type="{http://cnjuego.gob.es/sci/v2.13.xsd}Importe"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegistroOPT", propOrder = {
    "tipoJuego",
    "participacion",
    "participacionDevolucion",
    "premios",
    "premiosEspecie",
    "botes",
    "ajustesRed",
    "otros",
    "comision",
    "ggr"
})
@Entity(name = "RegistroOPT")
@Table(name = "REGISTROOPT", schema = "sgij")
public class RegistroOPT
    extends RegistroMensualBase
    implements Equals, HashCode
{

    @XmlElement(name = "TipoJuego", required = true)
    protected TipoJuego tipoJuego;
    @XmlElement(name = "Participacion", required = true)
    protected DesgloseOperador participacion;
    @XmlElement(name = "ParticipacionDevolucion", required = true)
    protected DesgloseOperador participacionDevolucion;
    @XmlElement(name = "Premios", required = true)
    protected DesgloseOperador premios;
    @XmlElement(name = "PremiosEspecie", required = true)
    protected DesgloseOperador premiosEspecie;
    @XmlElement(name = "Botes", required = true)
    protected DesgloseOperador botes;
    @XmlElement(name = "AjustesRed", required = true)
    protected DesgloseOperador ajustesRed;
    @XmlElement(name = "Otros", required = true)
    protected DesgloseOperadorConcepto otros;
    @XmlElement(name = "Comision", required = true)
    protected DesgloseOperador comision;
    @XmlElement(name = "GGR", required = true)
    protected Importe ggr;

    /**
     * Gets the value of the tipoJuego property.
     * 
     * @return
     *     possible object is
     *     {@link TipoJuego }
     *     
     */
    @Basic
    @Column(name = "TIPOJUEGO", length = 255)
    @Enumerated(EnumType.STRING)
    public TipoJuego getTipoJuego() {
        return tipoJuego;
    }

    /**
     * Sets the value of the tipoJuego property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoJuego }
     *     
     */
    public void setTipoJuego(TipoJuego value) {
        this.tipoJuego = value;
    }

    /**
     * Gets the value of the participacion property.
     * 
     * @return
     *     possible object is
     *     {@link DesgloseOperador }
     *     
     */
    @ManyToOne(targetEntity = DesgloseOperador.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "PARTICIPACION_REGISTROOPT_HJ_0")
    public DesgloseOperador getParticipacion() {
        return participacion;
    }

    /**
     * Sets the value of the participacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link DesgloseOperador }
     *     
     */
    public void setParticipacion(DesgloseOperador value) {
        this.participacion = value;
    }

    /**
     * Gets the value of the participacionDevolucion property.
     * 
     * @return
     *     possible object is
     *     {@link DesgloseOperador }
     *     
     */
    @ManyToOne(targetEntity = DesgloseOperador.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "PARTICIPACIONDEVOLUCION_REGI_0")
    public DesgloseOperador getParticipacionDevolucion() {
        return participacionDevolucion;
    }

    /**
     * Sets the value of the participacionDevolucion property.
     * 
     * @param value
     *     allowed object is
     *     {@link DesgloseOperador }
     *     
     */
    public void setParticipacionDevolucion(DesgloseOperador value) {
        this.participacionDevolucion = value;
    }

    /**
     * Gets the value of the premios property.
     * 
     * @return
     *     possible object is
     *     {@link DesgloseOperador }
     *     
     */
    @ManyToOne(targetEntity = DesgloseOperador.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "PREMIOS_REGISTROOPT_HJID")
    public DesgloseOperador getPremios() {
        return premios;
    }

    /**
     * Sets the value of the premios property.
     * 
     * @param value
     *     allowed object is
     *     {@link DesgloseOperador }
     *     
     */
    public void setPremios(DesgloseOperador value) {
        this.premios = value;
    }

    /**
     * Gets the value of the premiosEspecie property.
     * 
     * @return
     *     possible object is
     *     {@link DesgloseOperador }
     *     
     */
    @ManyToOne(targetEntity = DesgloseOperador.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "PREMIOSESPECIE_REGISTROOPT_H_0")
    public DesgloseOperador getPremiosEspecie() {
        return premiosEspecie;
    }

    /**
     * Sets the value of the premiosEspecie property.
     * 
     * @param value
     *     allowed object is
     *     {@link DesgloseOperador }
     *     
     */
    public void setPremiosEspecie(DesgloseOperador value) {
        this.premiosEspecie = value;
    }

    /**
     * Gets the value of the botes property.
     * 
     * @return
     *     possible object is
     *     {@link DesgloseOperador }
     *     
     */
    @ManyToOne(targetEntity = DesgloseOperador.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "BOTES_REGISTROOPT_HJID")
    public DesgloseOperador getBotes() {
        return botes;
    }

    /**
     * Sets the value of the botes property.
     * 
     * @param value
     *     allowed object is
     *     {@link DesgloseOperador }
     *     
     */
    public void setBotes(DesgloseOperador value) {
        this.botes = value;
    }

    /**
     * Gets the value of the ajustesRed property.
     * 
     * @return
     *     possible object is
     *     {@link DesgloseOperador }
     *     
     */
    @ManyToOne(targetEntity = DesgloseOperador.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "AJUSTESRED_REGISTROOPT_HJID")
    public DesgloseOperador getAjustesRed() {
        return ajustesRed;
    }

    /**
     * Sets the value of the ajustesRed property.
     * 
     * @param value
     *     allowed object is
     *     {@link DesgloseOperador }
     *     
     */
    public void setAjustesRed(DesgloseOperador value) {
        this.ajustesRed = value;
    }

    /**
     * Gets the value of the otros property.
     * 
     * @return
     *     possible object is
     *     {@link DesgloseOperadorConcepto }
     *     
     */
    @ManyToOne(targetEntity = DesgloseOperadorConcepto.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "OTROS_REGISTROOPT_HJID")
    public DesgloseOperadorConcepto getOtros() {
        return otros;
    }

    /**
     * Sets the value of the otros property.
     * 
     * @param value
     *     allowed object is
     *     {@link DesgloseOperadorConcepto }
     *     
     */
    public void setOtros(DesgloseOperadorConcepto value) {
        this.otros = value;
    }

    /**
     * Gets the value of the comision property.
     * 
     * @return
     *     possible object is
     *     {@link DesgloseOperador }
     *     
     */
    @ManyToOne(targetEntity = DesgloseOperador.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "COMISION_REGISTROOPT_HJID")
    public DesgloseOperador getComision() {
        return comision;
    }

    /**
     * Sets the value of the comision property.
     * 
     * @param value
     *     allowed object is
     *     {@link DesgloseOperador }
     *     
     */
    public void setComision(DesgloseOperador value) {
        this.comision = value;
    }

    /**
     * Gets the value of the ggr property.
     * 
     * @return
     *     possible object is
     *     {@link Importe }
     *     
     */
    @ManyToOne(targetEntity = Importe.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "GGR_REGISTROOPT_HJID")
    public Importe getGGR() {
        return ggr;
    }

    /**
     * Sets the value of the ggr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Importe }
     *     
     */
    public void setGGR(Importe value) {
        this.ggr = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof RegistroOPT)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final RegistroOPT that = ((RegistroOPT) object);
        {
            TipoJuego lhsTipoJuego;
            lhsTipoJuego = this.getTipoJuego();
            TipoJuego rhsTipoJuego;
            rhsTipoJuego = that.getTipoJuego();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "tipoJuego", lhsTipoJuego), LocatorUtils.property(thatLocator, "tipoJuego", rhsTipoJuego), lhsTipoJuego, rhsTipoJuego)) {
                return false;
            }
        }
        {
            DesgloseOperador lhsParticipacion;
            lhsParticipacion = this.getParticipacion();
            DesgloseOperador rhsParticipacion;
            rhsParticipacion = that.getParticipacion();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "participacion", lhsParticipacion), LocatorUtils.property(thatLocator, "participacion", rhsParticipacion), lhsParticipacion, rhsParticipacion)) {
                return false;
            }
        }
        {
            DesgloseOperador lhsParticipacionDevolucion;
            lhsParticipacionDevolucion = this.getParticipacionDevolucion();
            DesgloseOperador rhsParticipacionDevolucion;
            rhsParticipacionDevolucion = that.getParticipacionDevolucion();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "participacionDevolucion", lhsParticipacionDevolucion), LocatorUtils.property(thatLocator, "participacionDevolucion", rhsParticipacionDevolucion), lhsParticipacionDevolucion, rhsParticipacionDevolucion)) {
                return false;
            }
        }
        {
            DesgloseOperador lhsPremios;
            lhsPremios = this.getPremios();
            DesgloseOperador rhsPremios;
            rhsPremios = that.getPremios();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "premios", lhsPremios), LocatorUtils.property(thatLocator, "premios", rhsPremios), lhsPremios, rhsPremios)) {
                return false;
            }
        }
        {
            DesgloseOperador lhsPremiosEspecie;
            lhsPremiosEspecie = this.getPremiosEspecie();
            DesgloseOperador rhsPremiosEspecie;
            rhsPremiosEspecie = that.getPremiosEspecie();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "premiosEspecie", lhsPremiosEspecie), LocatorUtils.property(thatLocator, "premiosEspecie", rhsPremiosEspecie), lhsPremiosEspecie, rhsPremiosEspecie)) {
                return false;
            }
        }
        {
            DesgloseOperador lhsBotes;
            lhsBotes = this.getBotes();
            DesgloseOperador rhsBotes;
            rhsBotes = that.getBotes();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "botes", lhsBotes), LocatorUtils.property(thatLocator, "botes", rhsBotes), lhsBotes, rhsBotes)) {
                return false;
            }
        }
        {
            DesgloseOperador lhsAjustesRed;
            lhsAjustesRed = this.getAjustesRed();
            DesgloseOperador rhsAjustesRed;
            rhsAjustesRed = that.getAjustesRed();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "ajustesRed", lhsAjustesRed), LocatorUtils.property(thatLocator, "ajustesRed", rhsAjustesRed), lhsAjustesRed, rhsAjustesRed)) {
                return false;
            }
        }
        {
            DesgloseOperadorConcepto lhsOtros;
            lhsOtros = this.getOtros();
            DesgloseOperadorConcepto rhsOtros;
            rhsOtros = that.getOtros();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "otros", lhsOtros), LocatorUtils.property(thatLocator, "otros", rhsOtros), lhsOtros, rhsOtros)) {
                return false;
            }
        }
        {
            DesgloseOperador lhsComision;
            lhsComision = this.getComision();
            DesgloseOperador rhsComision;
            rhsComision = that.getComision();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "comision", lhsComision), LocatorUtils.property(thatLocator, "comision", rhsComision), lhsComision, rhsComision)) {
                return false;
            }
        }
        {
            Importe lhsGGR;
            lhsGGR = this.getGGR();
            Importe rhsGGR;
            rhsGGR = that.getGGR();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "ggr", lhsGGR), LocatorUtils.property(thatLocator, "ggr", rhsGGR), lhsGGR, rhsGGR)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            TipoJuego theTipoJuego;
            theTipoJuego = this.getTipoJuego();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "tipoJuego", theTipoJuego), currentHashCode, theTipoJuego);
        }
        {
            DesgloseOperador theParticipacion;
            theParticipacion = this.getParticipacion();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "participacion", theParticipacion), currentHashCode, theParticipacion);
        }
        {
            DesgloseOperador theParticipacionDevolucion;
            theParticipacionDevolucion = this.getParticipacionDevolucion();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "participacionDevolucion", theParticipacionDevolucion), currentHashCode, theParticipacionDevolucion);
        }
        {
            DesgloseOperador thePremios;
            thePremios = this.getPremios();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "premios", thePremios), currentHashCode, thePremios);
        }
        {
            DesgloseOperador thePremiosEspecie;
            thePremiosEspecie = this.getPremiosEspecie();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "premiosEspecie", thePremiosEspecie), currentHashCode, thePremiosEspecie);
        }
        {
            DesgloseOperador theBotes;
            theBotes = this.getBotes();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "botes", theBotes), currentHashCode, theBotes);
        }
        {
            DesgloseOperador theAjustesRed;
            theAjustesRed = this.getAjustesRed();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "ajustesRed", theAjustesRed), currentHashCode, theAjustesRed);
        }
        {
            DesgloseOperadorConcepto theOtros;
            theOtros = this.getOtros();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "otros", theOtros), currentHashCode, theOtros);
        }
        {
            DesgloseOperador theComision;
            theComision = this.getComision();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "comision", theComision), currentHashCode, theComision);
        }
        {
            Importe theGGR;
            theGGR = this.getGGR();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "ggr", theGGR), currentHashCode, theGGR);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
