//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 09:48:48 PM CEST 
//


package com.thingtrack.training.vertica.sgij.domain;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for RegistroConcurso complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegistroConcurso">
 *   &lt;complexContent>
 *     &lt;extension base="{http://cnjuego.gob.es/sci/v2.13.xsd}RegistroJUT">
 *       &lt;sequence>
 *         &lt;element name="NumeroParticipaciones" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="NumeroPremiados" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="NumeroLlamadas" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="PrecioMinutoLlamada" type="{http://cnjuego.gob.es/sci/v2.13.xsd}euros"/>
 *         &lt;element name="ImporteMaximoLlamada" type="{http://cnjuego.gob.es/sci/v2.13.xsd}euros"/>
 *         &lt;element name="ParticipacionLlamadas" type="{http://cnjuego.gob.es/sci/v2.13.xsd}euros"/>
 *         &lt;element name="STALlamadas" type="{http://cnjuego.gob.es/sci/v2.13.xsd}euros"/>
 *         &lt;element name="NumeroSMS" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="PrecioSMS" type="{http://cnjuego.gob.es/sci/v2.13.xsd}euros"/>
 *         &lt;element name="ParticipacionSMS" type="{http://cnjuego.gob.es/sci/v2.13.xsd}euros"/>
 *         &lt;element name="STASMS" type="{http://cnjuego.gob.es/sci/v2.13.xsd}euros"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegistroConcurso", propOrder = {
    "numeroParticipaciones",
    "numeroPremiados",
    "numeroLlamadas",
    "precioMinutoLlamada",
    "importeMaximoLlamada",
    "participacionLlamadas",
    "staLlamadas",
    "numeroSMS",
    "precioSMS",
    "participacionSMS",
    "stasms"
})
@Entity(name = "RegistroConcurso")
@Table(name = "REGISTROCONCURSO", schema = "sgij")
public class RegistroConcurso
    extends RegistroJUT
    implements Equals, HashCode
{

    @XmlElement(name = "NumeroParticipaciones", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numeroParticipaciones;
    @XmlElement(name = "NumeroPremiados", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numeroPremiados;
    @XmlElement(name = "NumeroLlamadas", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numeroLlamadas;
    @XmlElement(name = "PrecioMinutoLlamada", required = true)
    protected BigDecimal precioMinutoLlamada;
    @XmlElement(name = "ImporteMaximoLlamada", required = true)
    protected BigDecimal importeMaximoLlamada;
    @XmlElement(name = "ParticipacionLlamadas", required = true)
    protected BigDecimal participacionLlamadas;
    @XmlElement(name = "STALlamadas", required = true)
    protected BigDecimal staLlamadas;
    @XmlElement(name = "NumeroSMS", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numeroSMS;
    @XmlElement(name = "PrecioSMS", required = true)
    protected BigDecimal precioSMS;
    @XmlElement(name = "ParticipacionSMS", required = true)
    protected BigDecimal participacionSMS;
    @XmlElement(name = "STASMS", required = true)
    protected BigDecimal stasms;

    /**
     * Gets the value of the numeroParticipaciones property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "NUMEROPARTICIPACIONES", precision = 20, scale = 0)
    public BigInteger getNumeroParticipaciones() {
        return numeroParticipaciones;
    }

    /**
     * Sets the value of the numeroParticipaciones property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumeroParticipaciones(BigInteger value) {
        this.numeroParticipaciones = value;
    }

    /**
     * Gets the value of the numeroPremiados property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "NUMEROPREMIADOS", precision = 20, scale = 0)
    public BigInteger getNumeroPremiados() {
        return numeroPremiados;
    }

    /**
     * Sets the value of the numeroPremiados property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumeroPremiados(BigInteger value) {
        this.numeroPremiados = value;
    }

    /**
     * Gets the value of the numeroLlamadas property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "NUMEROLLAMADAS", precision = 20, scale = 0)
    public BigInteger getNumeroLlamadas() {
        return numeroLlamadas;
    }

    /**
     * Sets the value of the numeroLlamadas property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumeroLlamadas(BigInteger value) {
        this.numeroLlamadas = value;
    }

    /**
     * Gets the value of the precioMinutoLlamada property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    @Basic
    @Column(name = "PRECIOMINUTOLLAMADA", precision = 20, scale = 2)
    public BigDecimal getPrecioMinutoLlamada() {
        return precioMinutoLlamada;
    }

    /**
     * Sets the value of the precioMinutoLlamada property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrecioMinutoLlamada(BigDecimal value) {
        this.precioMinutoLlamada = value;
    }

    /**
     * Gets the value of the importeMaximoLlamada property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    @Basic
    @Column(name = "IMPORTEMAXIMOLLAMADA", precision = 20, scale = 2)
    public BigDecimal getImporteMaximoLlamada() {
        return importeMaximoLlamada;
    }

    /**
     * Sets the value of the importeMaximoLlamada property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setImporteMaximoLlamada(BigDecimal value) {
        this.importeMaximoLlamada = value;
    }

    /**
     * Gets the value of the participacionLlamadas property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    @Basic
    @Column(name = "PARTICIPACIONLLAMADAS", precision = 20, scale = 2)
    public BigDecimal getParticipacionLlamadas() {
        return participacionLlamadas;
    }

    /**
     * Sets the value of the participacionLlamadas property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setParticipacionLlamadas(BigDecimal value) {
        this.participacionLlamadas = value;
    }

    /**
     * Gets the value of the staLlamadas property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    @Basic
    @Column(name = "STALLAMADAS", precision = 20, scale = 2)
    public BigDecimal getSTALlamadas() {
        return staLlamadas;
    }

    /**
     * Sets the value of the staLlamadas property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSTALlamadas(BigDecimal value) {
        this.staLlamadas = value;
    }

    /**
     * Gets the value of the numeroSMS property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "NUMEROSMS", precision = 20, scale = 0)
    public BigInteger getNumeroSMS() {
        return numeroSMS;
    }

    /**
     * Sets the value of the numeroSMS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumeroSMS(BigInteger value) {
        this.numeroSMS = value;
    }

    /**
     * Gets the value of the precioSMS property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    @Basic
    @Column(name = "PRECIOSMS", precision = 20, scale = 2)
    public BigDecimal getPrecioSMS() {
        return precioSMS;
    }

    /**
     * Sets the value of the precioSMS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrecioSMS(BigDecimal value) {
        this.precioSMS = value;
    }

    /**
     * Gets the value of the participacionSMS property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    @Basic
    @Column(name = "PARTICIPACIONSMS", precision = 20, scale = 2)
    public BigDecimal getParticipacionSMS() {
        return participacionSMS;
    }

    /**
     * Sets the value of the participacionSMS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setParticipacionSMS(BigDecimal value) {
        this.participacionSMS = value;
    }

    /**
     * Gets the value of the stasms property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    @Basic
    @Column(name = "STASMS", precision = 20, scale = 2)
    public BigDecimal getSTASMS() {
        return stasms;
    }

    /**
     * Sets the value of the stasms property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSTASMS(BigDecimal value) {
        this.stasms = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof RegistroConcurso)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final RegistroConcurso that = ((RegistroConcurso) object);
        {
            BigInteger lhsNumeroParticipaciones;
            lhsNumeroParticipaciones = this.getNumeroParticipaciones();
            BigInteger rhsNumeroParticipaciones;
            rhsNumeroParticipaciones = that.getNumeroParticipaciones();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "numeroParticipaciones", lhsNumeroParticipaciones), LocatorUtils.property(thatLocator, "numeroParticipaciones", rhsNumeroParticipaciones), lhsNumeroParticipaciones, rhsNumeroParticipaciones)) {
                return false;
            }
        }
        {
            BigInteger lhsNumeroPremiados;
            lhsNumeroPremiados = this.getNumeroPremiados();
            BigInteger rhsNumeroPremiados;
            rhsNumeroPremiados = that.getNumeroPremiados();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "numeroPremiados", lhsNumeroPremiados), LocatorUtils.property(thatLocator, "numeroPremiados", rhsNumeroPremiados), lhsNumeroPremiados, rhsNumeroPremiados)) {
                return false;
            }
        }
        {
            BigInteger lhsNumeroLlamadas;
            lhsNumeroLlamadas = this.getNumeroLlamadas();
            BigInteger rhsNumeroLlamadas;
            rhsNumeroLlamadas = that.getNumeroLlamadas();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "numeroLlamadas", lhsNumeroLlamadas), LocatorUtils.property(thatLocator, "numeroLlamadas", rhsNumeroLlamadas), lhsNumeroLlamadas, rhsNumeroLlamadas)) {
                return false;
            }
        }
        {
            BigDecimal lhsPrecioMinutoLlamada;
            lhsPrecioMinutoLlamada = this.getPrecioMinutoLlamada();
            BigDecimal rhsPrecioMinutoLlamada;
            rhsPrecioMinutoLlamada = that.getPrecioMinutoLlamada();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "precioMinutoLlamada", lhsPrecioMinutoLlamada), LocatorUtils.property(thatLocator, "precioMinutoLlamada", rhsPrecioMinutoLlamada), lhsPrecioMinutoLlamada, rhsPrecioMinutoLlamada)) {
                return false;
            }
        }
        {
            BigDecimal lhsImporteMaximoLlamada;
            lhsImporteMaximoLlamada = this.getImporteMaximoLlamada();
            BigDecimal rhsImporteMaximoLlamada;
            rhsImporteMaximoLlamada = that.getImporteMaximoLlamada();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "importeMaximoLlamada", lhsImporteMaximoLlamada), LocatorUtils.property(thatLocator, "importeMaximoLlamada", rhsImporteMaximoLlamada), lhsImporteMaximoLlamada, rhsImporteMaximoLlamada)) {
                return false;
            }
        }
        {
            BigDecimal lhsParticipacionLlamadas;
            lhsParticipacionLlamadas = this.getParticipacionLlamadas();
            BigDecimal rhsParticipacionLlamadas;
            rhsParticipacionLlamadas = that.getParticipacionLlamadas();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "participacionLlamadas", lhsParticipacionLlamadas), LocatorUtils.property(thatLocator, "participacionLlamadas", rhsParticipacionLlamadas), lhsParticipacionLlamadas, rhsParticipacionLlamadas)) {
                return false;
            }
        }
        {
            BigDecimal lhsSTALlamadas;
            lhsSTALlamadas = this.getSTALlamadas();
            BigDecimal rhsSTALlamadas;
            rhsSTALlamadas = that.getSTALlamadas();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "staLlamadas", lhsSTALlamadas), LocatorUtils.property(thatLocator, "staLlamadas", rhsSTALlamadas), lhsSTALlamadas, rhsSTALlamadas)) {
                return false;
            }
        }
        {
            BigInteger lhsNumeroSMS;
            lhsNumeroSMS = this.getNumeroSMS();
            BigInteger rhsNumeroSMS;
            rhsNumeroSMS = that.getNumeroSMS();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "numeroSMS", lhsNumeroSMS), LocatorUtils.property(thatLocator, "numeroSMS", rhsNumeroSMS), lhsNumeroSMS, rhsNumeroSMS)) {
                return false;
            }
        }
        {
            BigDecimal lhsPrecioSMS;
            lhsPrecioSMS = this.getPrecioSMS();
            BigDecimal rhsPrecioSMS;
            rhsPrecioSMS = that.getPrecioSMS();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "precioSMS", lhsPrecioSMS), LocatorUtils.property(thatLocator, "precioSMS", rhsPrecioSMS), lhsPrecioSMS, rhsPrecioSMS)) {
                return false;
            }
        }
        {
            BigDecimal lhsParticipacionSMS;
            lhsParticipacionSMS = this.getParticipacionSMS();
            BigDecimal rhsParticipacionSMS;
            rhsParticipacionSMS = that.getParticipacionSMS();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "participacionSMS", lhsParticipacionSMS), LocatorUtils.property(thatLocator, "participacionSMS", rhsParticipacionSMS), lhsParticipacionSMS, rhsParticipacionSMS)) {
                return false;
            }
        }
        {
            BigDecimal lhsSTASMS;
            lhsSTASMS = this.getSTASMS();
            BigDecimal rhsSTASMS;
            rhsSTASMS = that.getSTASMS();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "stasms", lhsSTASMS), LocatorUtils.property(thatLocator, "stasms", rhsSTASMS), lhsSTASMS, rhsSTASMS)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            BigInteger theNumeroParticipaciones;
            theNumeroParticipaciones = this.getNumeroParticipaciones();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "numeroParticipaciones", theNumeroParticipaciones), currentHashCode, theNumeroParticipaciones);
        }
        {
            BigInteger theNumeroPremiados;
            theNumeroPremiados = this.getNumeroPremiados();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "numeroPremiados", theNumeroPremiados), currentHashCode, theNumeroPremiados);
        }
        {
            BigInteger theNumeroLlamadas;
            theNumeroLlamadas = this.getNumeroLlamadas();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "numeroLlamadas", theNumeroLlamadas), currentHashCode, theNumeroLlamadas);
        }
        {
            BigDecimal thePrecioMinutoLlamada;
            thePrecioMinutoLlamada = this.getPrecioMinutoLlamada();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "precioMinutoLlamada", thePrecioMinutoLlamada), currentHashCode, thePrecioMinutoLlamada);
        }
        {
            BigDecimal theImporteMaximoLlamada;
            theImporteMaximoLlamada = this.getImporteMaximoLlamada();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "importeMaximoLlamada", theImporteMaximoLlamada), currentHashCode, theImporteMaximoLlamada);
        }
        {
            BigDecimal theParticipacionLlamadas;
            theParticipacionLlamadas = this.getParticipacionLlamadas();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "participacionLlamadas", theParticipacionLlamadas), currentHashCode, theParticipacionLlamadas);
        }
        {
            BigDecimal theSTALlamadas;
            theSTALlamadas = this.getSTALlamadas();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "staLlamadas", theSTALlamadas), currentHashCode, theSTALlamadas);
        }
        {
            BigInteger theNumeroSMS;
            theNumeroSMS = this.getNumeroSMS();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "numeroSMS", theNumeroSMS), currentHashCode, theNumeroSMS);
        }
        {
            BigDecimal thePrecioSMS;
            thePrecioSMS = this.getPrecioSMS();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "precioSMS", thePrecioSMS), currentHashCode, thePrecioSMS);
        }
        {
            BigDecimal theParticipacionSMS;
            theParticipacionSMS = this.getParticipacionSMS();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "participacionSMS", theParticipacionSMS), currentHashCode, theParticipacionSMS);
        }
        {
            BigDecimal theSTASMS;
            theSTASMS = this.getSTASMS();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "stasms", theSTASMS), currentHashCode, theSTASMS);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
