//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 09:48:48 PM CEST 
//


package com.thingtrack.training.vertica.sgij.domain;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for RegistroJUT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegistroJUT">
 *   &lt;complexContent>
 *     &lt;extension base="{http://cnjuego.gob.es/sci/v2.13.xsd}RegistroBase">
 *       &lt;sequence>
 *         &lt;element name="JuegoId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="JuegoDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TipoJuego" type="{http://cnjuego.gob.es/sci/v2.13.xsd}TipoJuego"/>
 *         &lt;element name="FechaInicio" type="{http://cnjuego.gob.es/sci/v2.13.xsd}date-aaaammddhhmmssTZ"/>
 *         &lt;element name="FechaFin" type="{http://cnjuego.gob.es/sci/v2.13.xsd}date-aaaammddhhmmssTZ"/>
 *         &lt;element name="JuegoEnRed">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="S"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="JuegoAplazado" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="S"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="JuegoSuspendido" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="S"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="JuegoCancelado" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="S"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BooleanLI" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="S"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Totales">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Participacion" type="{http://cnjuego.gob.es/sci/v2.13.xsd}DesgloseOperador"/>
 *                   &lt;element name="ParticipacionDevolucion" type="{http://cnjuego.gob.es/sci/v2.13.xsd}DesgloseOperador"/>
 *                   &lt;element name="Premios" type="{http://cnjuego.gob.es/sci/v2.13.xsd}DesgloseOperador"/>
 *                   &lt;element name="PremiosEspecie" type="{http://cnjuego.gob.es/sci/v2.13.xsd}DesgloseOperador"/>
 *                   &lt;element name="Botes">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Total" type="{http://cnjuego.gob.es/sci/v2.13.xsd}Importe"/>
 *                             &lt;element name="Desglose" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="BoteId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="BoteDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Movimiento" type="{http://cnjuego.gob.es/sci/v2.13.xsd}Importe"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegistroJUT", propOrder = {
    "juegoId",
    "juegoDesc",
    "tipoJuego",
    "fechaInicio",
    "fechaFin",
    "juegoEnRed",
    "juegoAplazado",
    "juegoSuspendido",
    "juegoCancelado",
    "booleanLI",
    "totales"
})
@XmlSeeAlso({
    RegistroPokerCash.class,
    RegistroPuntoBanca.class,
    RegistroPokerTorneo.class,
    RegistroLoteria.class,
    RegistroApuesta.class,
    RegistroBingo.class,
    RegistroConcurso.class,
    RegistroSesion.class
})
@Entity(name = "RegistroJUT")
@Table(name = "REGISTROJUT", schema = "sgij")
public abstract class RegistroJUT
    extends RegistroBase
    implements Equals, HashCode
{

    @XmlElement(name = "JuegoId", required = true)
    protected String juegoId;
    @XmlElement(name = "JuegoDesc", required = true)
    protected String juegoDesc;
    @XmlElement(name = "TipoJuego", required = true)
    protected TipoJuego tipoJuego;
    @XmlElement(name = "FechaInicio", required = true)
    protected String fechaInicio;
    @XmlElement(name = "FechaFin", required = true)
    protected String fechaFin;
    @XmlElement(name = "JuegoEnRed", required = true)
    protected String juegoEnRed;
    @XmlElement(name = "JuegoAplazado")
    protected String juegoAplazado;
    @XmlElement(name = "JuegoSuspendido")
    protected String juegoSuspendido;
    @XmlElement(name = "JuegoCancelado")
    protected String juegoCancelado;
    @XmlElement(name = "BooleanLI")
    protected String booleanLI;
    @XmlElement(name = "Totales", required = true)
    protected RegistroJUT.Totales totales;

    /**
     * Gets the value of the juegoId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "JUEGOID", length = 255)
    public String getJuegoId() {
        return juegoId;
    }

    /**
     * Sets the value of the juegoId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJuegoId(String value) {
        this.juegoId = value;
    }

    /**
     * Gets the value of the juegoDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "JUEGODESC", length = 255)
    public String getJuegoDesc() {
        return juegoDesc;
    }

    /**
     * Sets the value of the juegoDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJuegoDesc(String value) {
        this.juegoDesc = value;
    }

    /**
     * Gets the value of the tipoJuego property.
     * 
     * @return
     *     possible object is
     *     {@link TipoJuego }
     *     
     */
    @Basic
    @Column(name = "TIPOJUEGO", length = 255)
    @Enumerated(EnumType.STRING)
    public TipoJuego getTipoJuego() {
        return tipoJuego;
    }

    /**
     * Sets the value of the tipoJuego property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoJuego }
     *     
     */
    public void setTipoJuego(TipoJuego value) {
        this.tipoJuego = value;
    }

    /**
     * Gets the value of the fechaInicio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "FECHAINICIO", length = 255)
    public String getFechaInicio() {
        return fechaInicio;
    }

    /**
     * Sets the value of the fechaInicio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaInicio(String value) {
        this.fechaInicio = value;
    }

    /**
     * Gets the value of the fechaFin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "FECHAFIN", length = 255)
    public String getFechaFin() {
        return fechaFin;
    }

    /**
     * Sets the value of the fechaFin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaFin(String value) {
        this.fechaFin = value;
    }

    /**
     * Gets the value of the juegoEnRed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "JUEGOENRED")
    public String getJuegoEnRed() {
        return juegoEnRed;
    }

    /**
     * Sets the value of the juegoEnRed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJuegoEnRed(String value) {
        this.juegoEnRed = value;
    }

    /**
     * Gets the value of the juegoAplazado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "JUEGOAPLAZADO")
    public String getJuegoAplazado() {
        return juegoAplazado;
    }

    /**
     * Sets the value of the juegoAplazado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJuegoAplazado(String value) {
        this.juegoAplazado = value;
    }

    /**
     * Gets the value of the juegoSuspendido property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "JUEGOSUSPENDIDO")
    public String getJuegoSuspendido() {
        return juegoSuspendido;
    }

    /**
     * Sets the value of the juegoSuspendido property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJuegoSuspendido(String value) {
        this.juegoSuspendido = value;
    }

    /**
     * Gets the value of the juegoCancelado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "JUEGOCANCELADO")
    public String getJuegoCancelado() {
        return juegoCancelado;
    }

    /**
     * Sets the value of the juegoCancelado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJuegoCancelado(String value) {
        this.juegoCancelado = value;
    }

    /**
     * Gets the value of the booleanLI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "BOOLEANLI")
    public String getBooleanLI() {
        return booleanLI;
    }

    /**
     * Sets the value of the booleanLI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBooleanLI(String value) {
        this.booleanLI = value;
    }

    /**
     * Gets the value of the totales property.
     * 
     * @return
     *     possible object is
     *     {@link RegistroJUT.Totales }
     *     
     */
    @ManyToOne(targetEntity = RegistroJUT.Totales.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "TOTALES_REGISTROJUT_HJID")
    public RegistroJUT.Totales getTotales() {
        return totales;
    }

    /**
     * Sets the value of the totales property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegistroJUT.Totales }
     *     
     */
    public void setTotales(RegistroJUT.Totales value) {
        this.totales = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof RegistroJUT)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final RegistroJUT that = ((RegistroJUT) object);
        {
            String lhsJuegoId;
            lhsJuegoId = this.getJuegoId();
            String rhsJuegoId;
            rhsJuegoId = that.getJuegoId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "juegoId", lhsJuegoId), LocatorUtils.property(thatLocator, "juegoId", rhsJuegoId), lhsJuegoId, rhsJuegoId)) {
                return false;
            }
        }
        {
            String lhsJuegoDesc;
            lhsJuegoDesc = this.getJuegoDesc();
            String rhsJuegoDesc;
            rhsJuegoDesc = that.getJuegoDesc();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "juegoDesc", lhsJuegoDesc), LocatorUtils.property(thatLocator, "juegoDesc", rhsJuegoDesc), lhsJuegoDesc, rhsJuegoDesc)) {
                return false;
            }
        }
        {
            TipoJuego lhsTipoJuego;
            lhsTipoJuego = this.getTipoJuego();
            TipoJuego rhsTipoJuego;
            rhsTipoJuego = that.getTipoJuego();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "tipoJuego", lhsTipoJuego), LocatorUtils.property(thatLocator, "tipoJuego", rhsTipoJuego), lhsTipoJuego, rhsTipoJuego)) {
                return false;
            }
        }
        {
            String lhsFechaInicio;
            lhsFechaInicio = this.getFechaInicio();
            String rhsFechaInicio;
            rhsFechaInicio = that.getFechaInicio();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "fechaInicio", lhsFechaInicio), LocatorUtils.property(thatLocator, "fechaInicio", rhsFechaInicio), lhsFechaInicio, rhsFechaInicio)) {
                return false;
            }
        }
        {
            String lhsFechaFin;
            lhsFechaFin = this.getFechaFin();
            String rhsFechaFin;
            rhsFechaFin = that.getFechaFin();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "fechaFin", lhsFechaFin), LocatorUtils.property(thatLocator, "fechaFin", rhsFechaFin), lhsFechaFin, rhsFechaFin)) {
                return false;
            }
        }
        {
            String lhsJuegoEnRed;
            lhsJuegoEnRed = this.getJuegoEnRed();
            String rhsJuegoEnRed;
            rhsJuegoEnRed = that.getJuegoEnRed();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "juegoEnRed", lhsJuegoEnRed), LocatorUtils.property(thatLocator, "juegoEnRed", rhsJuegoEnRed), lhsJuegoEnRed, rhsJuegoEnRed)) {
                return false;
            }
        }
        {
            String lhsJuegoAplazado;
            lhsJuegoAplazado = this.getJuegoAplazado();
            String rhsJuegoAplazado;
            rhsJuegoAplazado = that.getJuegoAplazado();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "juegoAplazado", lhsJuegoAplazado), LocatorUtils.property(thatLocator, "juegoAplazado", rhsJuegoAplazado), lhsJuegoAplazado, rhsJuegoAplazado)) {
                return false;
            }
        }
        {
            String lhsJuegoSuspendido;
            lhsJuegoSuspendido = this.getJuegoSuspendido();
            String rhsJuegoSuspendido;
            rhsJuegoSuspendido = that.getJuegoSuspendido();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "juegoSuspendido", lhsJuegoSuspendido), LocatorUtils.property(thatLocator, "juegoSuspendido", rhsJuegoSuspendido), lhsJuegoSuspendido, rhsJuegoSuspendido)) {
                return false;
            }
        }
        {
            String lhsJuegoCancelado;
            lhsJuegoCancelado = this.getJuegoCancelado();
            String rhsJuegoCancelado;
            rhsJuegoCancelado = that.getJuegoCancelado();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "juegoCancelado", lhsJuegoCancelado), LocatorUtils.property(thatLocator, "juegoCancelado", rhsJuegoCancelado), lhsJuegoCancelado, rhsJuegoCancelado)) {
                return false;
            }
        }
        {
            String lhsBooleanLI;
            lhsBooleanLI = this.getBooleanLI();
            String rhsBooleanLI;
            rhsBooleanLI = that.getBooleanLI();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "booleanLI", lhsBooleanLI), LocatorUtils.property(thatLocator, "booleanLI", rhsBooleanLI), lhsBooleanLI, rhsBooleanLI)) {
                return false;
            }
        }
        {
            RegistroJUT.Totales lhsTotales;
            lhsTotales = this.getTotales();
            RegistroJUT.Totales rhsTotales;
            rhsTotales = that.getTotales();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "totales", lhsTotales), LocatorUtils.property(thatLocator, "totales", rhsTotales), lhsTotales, rhsTotales)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            String theJuegoId;
            theJuegoId = this.getJuegoId();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "juegoId", theJuegoId), currentHashCode, theJuegoId);
        }
        {
            String theJuegoDesc;
            theJuegoDesc = this.getJuegoDesc();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "juegoDesc", theJuegoDesc), currentHashCode, theJuegoDesc);
        }
        {
            TipoJuego theTipoJuego;
            theTipoJuego = this.getTipoJuego();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "tipoJuego", theTipoJuego), currentHashCode, theTipoJuego);
        }
        {
            String theFechaInicio;
            theFechaInicio = this.getFechaInicio();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "fechaInicio", theFechaInicio), currentHashCode, theFechaInicio);
        }
        {
            String theFechaFin;
            theFechaFin = this.getFechaFin();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "fechaFin", theFechaFin), currentHashCode, theFechaFin);
        }
        {
            String theJuegoEnRed;
            theJuegoEnRed = this.getJuegoEnRed();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "juegoEnRed", theJuegoEnRed), currentHashCode, theJuegoEnRed);
        }
        {
            String theJuegoAplazado;
            theJuegoAplazado = this.getJuegoAplazado();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "juegoAplazado", theJuegoAplazado), currentHashCode, theJuegoAplazado);
        }
        {
            String theJuegoSuspendido;
            theJuegoSuspendido = this.getJuegoSuspendido();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "juegoSuspendido", theJuegoSuspendido), currentHashCode, theJuegoSuspendido);
        }
        {
            String theJuegoCancelado;
            theJuegoCancelado = this.getJuegoCancelado();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "juegoCancelado", theJuegoCancelado), currentHashCode, theJuegoCancelado);
        }
        {
            String theBooleanLI;
            theBooleanLI = this.getBooleanLI();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "booleanLI", theBooleanLI), currentHashCode, theBooleanLI);
        }
        {
            RegistroJUT.Totales theTotales;
            theTotales = this.getTotales();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "totales", theTotales), currentHashCode, theTotales);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Participacion" type="{http://cnjuego.gob.es/sci/v2.13.xsd}DesgloseOperador"/>
     *         &lt;element name="ParticipacionDevolucion" type="{http://cnjuego.gob.es/sci/v2.13.xsd}DesgloseOperador"/>
     *         &lt;element name="Premios" type="{http://cnjuego.gob.es/sci/v2.13.xsd}DesgloseOperador"/>
     *         &lt;element name="PremiosEspecie" type="{http://cnjuego.gob.es/sci/v2.13.xsd}DesgloseOperador"/>
     *         &lt;element name="Botes">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Total" type="{http://cnjuego.gob.es/sci/v2.13.xsd}Importe"/>
     *                   &lt;element name="Desglose" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="BoteId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="BoteDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Movimiento" type="{http://cnjuego.gob.es/sci/v2.13.xsd}Importe"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "participacion",
        "participacionDevolucion",
        "premios",
        "premiosEspecie",
        "botes"
    })
    @Entity(name = "RegistroJUT$Totales")
    @Table(name = "TOTALES", schema = "sgij")
    @Inheritance(strategy = InheritanceType.JOINED)
    public static class Totales
        implements Equals, HashCode
    {

        @XmlElement(name = "Participacion", required = true)
        protected DesgloseOperador participacion;
        @XmlElement(name = "ParticipacionDevolucion", required = true)
        protected DesgloseOperador participacionDevolucion;
        @XmlElement(name = "Premios", required = true)
        protected DesgloseOperador premios;
        @XmlElement(name = "PremiosEspecie", required = true)
        protected DesgloseOperador premiosEspecie;
        @XmlElement(name = "Botes", required = true)
        protected RegistroJUT.Totales.Botes botes;
        @XmlAttribute(name = "Hjid")
        protected Long hjid;

        /**
         * Gets the value of the participacion property.
         * 
         * @return
         *     possible object is
         *     {@link DesgloseOperador }
         *     
         */
        @ManyToOne(targetEntity = DesgloseOperador.class, cascade = {
            CascadeType.ALL
        })
        @JoinColumn(name = "PARTICIPACION_TOTALES_HJID")
        public DesgloseOperador getParticipacion() {
            return participacion;
        }

        /**
         * Sets the value of the participacion property.
         * 
         * @param value
         *     allowed object is
         *     {@link DesgloseOperador }
         *     
         */
        public void setParticipacion(DesgloseOperador value) {
            this.participacion = value;
        }

        /**
         * Gets the value of the participacionDevolucion property.
         * 
         * @return
         *     possible object is
         *     {@link DesgloseOperador }
         *     
         */
        @ManyToOne(targetEntity = DesgloseOperador.class, cascade = {
            CascadeType.ALL
        })
        @JoinColumn(name = "PARTICIPACIONDEVOLUCION_TOTA_0")
        public DesgloseOperador getParticipacionDevolucion() {
            return participacionDevolucion;
        }

        /**
         * Sets the value of the participacionDevolucion property.
         * 
         * @param value
         *     allowed object is
         *     {@link DesgloseOperador }
         *     
         */
        public void setParticipacionDevolucion(DesgloseOperador value) {
            this.participacionDevolucion = value;
        }

        /**
         * Gets the value of the premios property.
         * 
         * @return
         *     possible object is
         *     {@link DesgloseOperador }
         *     
         */
        @ManyToOne(targetEntity = DesgloseOperador.class, cascade = {
            CascadeType.ALL
        })
        @JoinColumn(name = "PREMIOS_TOTALES_HJID")
        public DesgloseOperador getPremios() {
            return premios;
        }

        /**
         * Sets the value of the premios property.
         * 
         * @param value
         *     allowed object is
         *     {@link DesgloseOperador }
         *     
         */
        public void setPremios(DesgloseOperador value) {
            this.premios = value;
        }

        /**
         * Gets the value of the premiosEspecie property.
         * 
         * @return
         *     possible object is
         *     {@link DesgloseOperador }
         *     
         */
        @ManyToOne(targetEntity = DesgloseOperador.class, cascade = {
            CascadeType.ALL
        })
        @JoinColumn(name = "PREMIOSESPECIE_TOTALES_HJID")
        public DesgloseOperador getPremiosEspecie() {
            return premiosEspecie;
        }

        /**
         * Sets the value of the premiosEspecie property.
         * 
         * @param value
         *     allowed object is
         *     {@link DesgloseOperador }
         *     
         */
        public void setPremiosEspecie(DesgloseOperador value) {
            this.premiosEspecie = value;
        }

        /**
         * Gets the value of the botes property.
         * 
         * @return
         *     possible object is
         *     {@link RegistroJUT.Totales.Botes }
         *     
         */
        @ManyToOne(targetEntity = com.thingtrack.training.vertica.sgij.domain.RegistroJUT.Totales.Botes.class, cascade = {
            CascadeType.ALL
        })
        @JoinColumn(name = "BOTES_TOTALES_HJID")
        public RegistroJUT.Totales.Botes getBotes() {
            return botes;
        }

        /**
         * Sets the value of the botes property.
         * 
         * @param value
         *     allowed object is
         *     {@link RegistroJUT.Totales.Botes }
         *     
         */
        public void setBotes(RegistroJUT.Totales.Botes value) {
            this.botes = value;
        }

        /**
         * Gets the value of the hjid property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        @Id
        @Column(name = "HJID")
        @GeneratedValue(strategy = GenerationType.AUTO)
        public Long getHjid() {
            return hjid;
        }

        /**
         * Sets the value of the hjid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setHjid(Long value) {
            this.hjid = value;
        }

        public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
            if (!(object instanceof RegistroJUT.Totales)) {
                return false;
            }
            if (this == object) {
                return true;
            }
            final RegistroJUT.Totales that = ((RegistroJUT.Totales) object);
            {
                DesgloseOperador lhsParticipacion;
                lhsParticipacion = this.getParticipacion();
                DesgloseOperador rhsParticipacion;
                rhsParticipacion = that.getParticipacion();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "participacion", lhsParticipacion), LocatorUtils.property(thatLocator, "participacion", rhsParticipacion), lhsParticipacion, rhsParticipacion)) {
                    return false;
                }
            }
            {
                DesgloseOperador lhsParticipacionDevolucion;
                lhsParticipacionDevolucion = this.getParticipacionDevolucion();
                DesgloseOperador rhsParticipacionDevolucion;
                rhsParticipacionDevolucion = that.getParticipacionDevolucion();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "participacionDevolucion", lhsParticipacionDevolucion), LocatorUtils.property(thatLocator, "participacionDevolucion", rhsParticipacionDevolucion), lhsParticipacionDevolucion, rhsParticipacionDevolucion)) {
                    return false;
                }
            }
            {
                DesgloseOperador lhsPremios;
                lhsPremios = this.getPremios();
                DesgloseOperador rhsPremios;
                rhsPremios = that.getPremios();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "premios", lhsPremios), LocatorUtils.property(thatLocator, "premios", rhsPremios), lhsPremios, rhsPremios)) {
                    return false;
                }
            }
            {
                DesgloseOperador lhsPremiosEspecie;
                lhsPremiosEspecie = this.getPremiosEspecie();
                DesgloseOperador rhsPremiosEspecie;
                rhsPremiosEspecie = that.getPremiosEspecie();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "premiosEspecie", lhsPremiosEspecie), LocatorUtils.property(thatLocator, "premiosEspecie", rhsPremiosEspecie), lhsPremiosEspecie, rhsPremiosEspecie)) {
                    return false;
                }
            }
            {
                RegistroJUT.Totales.Botes lhsBotes;
                lhsBotes = this.getBotes();
                RegistroJUT.Totales.Botes rhsBotes;
                rhsBotes = that.getBotes();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "botes", lhsBotes), LocatorUtils.property(thatLocator, "botes", rhsBotes), lhsBotes, rhsBotes)) {
                    return false;
                }
            }
            return true;
        }

        public boolean equals(Object object) {
            final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
            return equals(null, null, object, strategy);
        }

        public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
            int currentHashCode = 1;
            {
                DesgloseOperador theParticipacion;
                theParticipacion = this.getParticipacion();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "participacion", theParticipacion), currentHashCode, theParticipacion);
            }
            {
                DesgloseOperador theParticipacionDevolucion;
                theParticipacionDevolucion = this.getParticipacionDevolucion();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "participacionDevolucion", theParticipacionDevolucion), currentHashCode, theParticipacionDevolucion);
            }
            {
                DesgloseOperador thePremios;
                thePremios = this.getPremios();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "premios", thePremios), currentHashCode, thePremios);
            }
            {
                DesgloseOperador thePremiosEspecie;
                thePremiosEspecie = this.getPremiosEspecie();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "premiosEspecie", thePremiosEspecie), currentHashCode, thePremiosEspecie);
            }
            {
                RegistroJUT.Totales.Botes theBotes;
                theBotes = this.getBotes();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "botes", theBotes), currentHashCode, theBotes);
            }
            return currentHashCode;
        }

        public int hashCode() {
            final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
            return this.hashCode(null, strategy);
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Total" type="{http://cnjuego.gob.es/sci/v2.13.xsd}Importe"/>
         *         &lt;element name="Desglose" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="BoteId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="BoteDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Movimiento" type="{http://cnjuego.gob.es/sci/v2.13.xsd}Importe"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "total",
            "desglose"
        })
        @Entity(name = "RegistroJUT$Totales$Botes")
        @Table(name = "BOTES", schema = "sgij")
        @Inheritance(strategy = InheritanceType.JOINED)
        public static class Botes
            implements Equals, HashCode
        {

            @XmlElement(name = "Total", required = true)
            protected Importe total;
            @XmlElement(name = "Desglose")
            protected List<RegistroJUT.Totales.Botes.Desglose> desglose;
            @XmlAttribute(name = "Hjid")
            protected Long hjid;

            /**
             * Gets the value of the total property.
             * 
             * @return
             *     possible object is
             *     {@link Importe }
             *     
             */
            @ManyToOne(targetEntity = Importe.class, cascade = {
                CascadeType.ALL
            })
            @JoinColumn(name = "TOTAL_BOTES_HJID")
            public Importe getTotal() {
                return total;
            }

            /**
             * Sets the value of the total property.
             * 
             * @param value
             *     allowed object is
             *     {@link Importe }
             *     
             */
            public void setTotal(Importe value) {
                this.total = value;
            }

            /**
             * Gets the value of the desglose property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the desglose property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDesglose().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link RegistroJUT.Totales.Botes.Desglose }
             * 
             * 
             */
            @OneToMany(targetEntity = com.thingtrack.training.vertica.sgij.domain.RegistroJUT.Totales.Botes.Desglose.class, cascade = {
                CascadeType.ALL
            })
            @JoinColumn(name = "DESGLOSE_BOTES_HJID")
            public List<RegistroJUT.Totales.Botes.Desglose> getDesglose() {
                if (desglose == null) {
                    desglose = new ArrayList<RegistroJUT.Totales.Botes.Desglose>();
                }
                return this.desglose;
            }

            /**
             * 
             * 
             */
            public void setDesglose(List<RegistroJUT.Totales.Botes.Desglose> desglose) {
                this.desglose = desglose;
            }

            /**
             * Gets the value of the hjid property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            @Id
            @Column(name = "HJID")
            @GeneratedValue(strategy = GenerationType.AUTO)
            public Long getHjid() {
                return hjid;
            }

            /**
             * Sets the value of the hjid property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setHjid(Long value) {
                this.hjid = value;
            }

            public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
                if (!(object instanceof RegistroJUT.Totales.Botes)) {
                    return false;
                }
                if (this == object) {
                    return true;
                }
                final RegistroJUT.Totales.Botes that = ((RegistroJUT.Totales.Botes) object);
                {
                    Importe lhsTotal;
                    lhsTotal = this.getTotal();
                    Importe rhsTotal;
                    rhsTotal = that.getTotal();
                    if (!strategy.equals(LocatorUtils.property(thisLocator, "total", lhsTotal), LocatorUtils.property(thatLocator, "total", rhsTotal), lhsTotal, rhsTotal)) {
                        return false;
                    }
                }
                {
                    List<RegistroJUT.Totales.Botes.Desglose> lhsDesglose;
                    lhsDesglose = (((this.desglose!= null)&&(!this.desglose.isEmpty()))?this.getDesglose():null);
                    List<RegistroJUT.Totales.Botes.Desglose> rhsDesglose;
                    rhsDesglose = (((that.desglose!= null)&&(!that.desglose.isEmpty()))?that.getDesglose():null);
                    if (!strategy.equals(LocatorUtils.property(thisLocator, "desglose", lhsDesglose), LocatorUtils.property(thatLocator, "desglose", rhsDesglose), lhsDesglose, rhsDesglose)) {
                        return false;
                    }
                }
                return true;
            }

            public boolean equals(Object object) {
                final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
                return equals(null, null, object, strategy);
            }

            public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
                int currentHashCode = 1;
                {
                    Importe theTotal;
                    theTotal = this.getTotal();
                    currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "total", theTotal), currentHashCode, theTotal);
                }
                {
                    List<RegistroJUT.Totales.Botes.Desglose> theDesglose;
                    theDesglose = (((this.desglose!= null)&&(!this.desglose.isEmpty()))?this.getDesglose():null);
                    currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "desglose", theDesglose), currentHashCode, theDesglose);
                }
                return currentHashCode;
            }

            public int hashCode() {
                final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
                return this.hashCode(null, strategy);
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="BoteId" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="BoteDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Movimiento" type="{http://cnjuego.gob.es/sci/v2.13.xsd}Importe"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "boteId",
                "boteDesc",
                "movimiento"
            })
            @Entity(name = "RegistroJUT$Totales$Botes$Desglose")
            @Table(name = "DESGLOSE", schema = "sgij")
            @Inheritance(strategy = InheritanceType.JOINED)
            public static class Desglose
                implements Equals, HashCode
            {

                @XmlElement(name = "BoteId", required = true)
                protected String boteId;
                @XmlElement(name = "BoteDesc", required = true)
                protected String boteDesc;
                @XmlElement(name = "Movimiento", required = true)
                protected Importe movimiento;
                @XmlAttribute(name = "Hjid")
                protected Long hjid;

                /**
                 * Gets the value of the boteId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                @Basic
                @Column(name = "BOTEID", length = 255)
                public String getBoteId() {
                    return boteId;
                }

                /**
                 * Sets the value of the boteId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setBoteId(String value) {
                    this.boteId = value;
                }

                /**
                 * Gets the value of the boteDesc property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                @Basic
                @Column(name = "BOTEDESC", length = 255)
                public String getBoteDesc() {
                    return boteDesc;
                }

                /**
                 * Sets the value of the boteDesc property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setBoteDesc(String value) {
                    this.boteDesc = value;
                }

                /**
                 * Gets the value of the movimiento property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Importe }
                 *     
                 */
                @ManyToOne(targetEntity = Importe.class, cascade = {
                    CascadeType.ALL
                })
                @JoinColumn(name = "MOVIMIENTO_DESGLOSE_HJID")
                public Importe getMovimiento() {
                    return movimiento;
                }

                /**
                 * Sets the value of the movimiento property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Importe }
                 *     
                 */
                public void setMovimiento(Importe value) {
                    this.movimiento = value;
                }

                /**
                 * Gets the value of the hjid property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Long }
                 *     
                 */
                @Id
                @Column(name = "HJID")
                @GeneratedValue(strategy = GenerationType.AUTO)
                public Long getHjid() {
                    return hjid;
                }

                /**
                 * Sets the value of the hjid property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Long }
                 *     
                 */
                public void setHjid(Long value) {
                    this.hjid = value;
                }

                public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
                    if (!(object instanceof RegistroJUT.Totales.Botes.Desglose)) {
                        return false;
                    }
                    if (this == object) {
                        return true;
                    }
                    final RegistroJUT.Totales.Botes.Desglose that = ((RegistroJUT.Totales.Botes.Desglose) object);
                    {
                        String lhsBoteId;
                        lhsBoteId = this.getBoteId();
                        String rhsBoteId;
                        rhsBoteId = that.getBoteId();
                        if (!strategy.equals(LocatorUtils.property(thisLocator, "boteId", lhsBoteId), LocatorUtils.property(thatLocator, "boteId", rhsBoteId), lhsBoteId, rhsBoteId)) {
                            return false;
                        }
                    }
                    {
                        String lhsBoteDesc;
                        lhsBoteDesc = this.getBoteDesc();
                        String rhsBoteDesc;
                        rhsBoteDesc = that.getBoteDesc();
                        if (!strategy.equals(LocatorUtils.property(thisLocator, "boteDesc", lhsBoteDesc), LocatorUtils.property(thatLocator, "boteDesc", rhsBoteDesc), lhsBoteDesc, rhsBoteDesc)) {
                            return false;
                        }
                    }
                    {
                        Importe lhsMovimiento;
                        lhsMovimiento = this.getMovimiento();
                        Importe rhsMovimiento;
                        rhsMovimiento = that.getMovimiento();
                        if (!strategy.equals(LocatorUtils.property(thisLocator, "movimiento", lhsMovimiento), LocatorUtils.property(thatLocator, "movimiento", rhsMovimiento), lhsMovimiento, rhsMovimiento)) {
                            return false;
                        }
                    }
                    return true;
                }

                public boolean equals(Object object) {
                    final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
                    return equals(null, null, object, strategy);
                }

                public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
                    int currentHashCode = 1;
                    {
                        String theBoteId;
                        theBoteId = this.getBoteId();
                        currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "boteId", theBoteId), currentHashCode, theBoteId);
                    }
                    {
                        String theBoteDesc;
                        theBoteDesc = this.getBoteDesc();
                        currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "boteDesc", theBoteDesc), currentHashCode, theBoteDesc);
                    }
                    {
                        Importe theMovimiento;
                        theMovimiento = this.getMovimiento();
                        currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "movimiento", theMovimiento), currentHashCode, theMovimiento);
                    }
                    return currentHashCode;
                }

                public int hashCode() {
                    final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
                    return this.hashCode(null, strategy);
                }

            }

        }

    }

}
